import type {
  EnrichableOpportunityVenueV2,
  OpportunityVenueV2Response,
} from "./types.js";

export const enrichOpportunityVenueV2Response = (
  row: EnrichableOpportunityVenueV2,
): OpportunityVenueV2Response => ({
  id: row.id,
  opportunityType: row.opportunityType,
  eventName: row.eventName ?? "",
  eventActivityGroup: row.eventActivityGroup,
  eventType: row.eventType,
  eventDescription: row.eventDescription,
  eventAddressLine1: row.eventAddressLine1,
  eventAddressLine2: row.eventAddressLine2,
  eventCity: row.eventCity,
  eventRegion: row.eventRegion,
  eventPostcode: row.eventPostcode,
  eventCountry: row.eventCountry,
  latitude: row.latitude,
  longitude: row.longitude,
  eventPhysicalSetting: row.eventPhysicalSetting,
  eventDetailedWeatherSuitability: row.eventDetailedWeatherSuitability,
  eventStartDate: row.eventStartDate,
  eventEndDate: row.eventEndDate,
  eventDaysTotal: row.eventDaysTotal,
  eventDailyMultiSession: row.eventDailyMultiSession,
  eventTimetableWeekly: row.eventTimetableWeekly,
  eventDailyFixedTimings: row.eventDailyFixedTimings,
  eventDailyFixedStartTime: row.eventDailyFixedStartTime,
  eventDailyFixedEndTime: row.eventDailyFixedEndTime,
  eventDailyMultiSessionTotal: row.eventDailyMultiSessionTotal,
  eventDailyMultiSessionTimings: row.eventDailyMultiSessionTimings,
  eventWeeklyFixedStartTime: row.eventWeeklyFixedStartTime,
  eventWeeklyFixedEndTime: row.eventWeeklyFixedEndTime,
  eventMixedTimingsMondayStart: row.eventMixedTimingsMondayStart,
  eventMixedTimingsMondayEnd: row.eventMixedTimingsMondayEnd,
  eventMixedTimingsTuesdayStart: row.eventMixedTimingsTuesdayStart,
  eventMixedTimingsTuesdayEnd: row.eventMixedTimingsTuesdayEnd,
  eventMixedTimingsWednesdayStart: row.eventMixedTimingsWednesdayStart,
  eventMixedTimingsWednesdayEnd: row.eventMixedTimingsWednesdayEnd,
  eventMixedTimingsThursdayStart: row.eventMixedTimingsThursdayStart,
  eventMixedTimingsThursdayEnd: row.eventMixedTimingsThursdayEnd,
  eventMixedTimingsFridayStart: row.eventMixedTimingsFridayStart,
  eventMixedTimingsFridayEnd: row.eventMixedTimingsFridayEnd,
  eventMixedTimingsSaturdayStart: row.eventMixedTimingsSaturdayStart,
  eventMixedTimingsSaturdayEnd: row.eventMixedTimingsSaturdayEnd,
  eventMixedTimingsSundayStart: row.eventMixedTimingsSundayStart,
  eventMixedTimingsSundayEnd: row.eventMixedTimingsSundayEnd,
  ticketSalesStartDate: row.ticketSalesStartDate,
  eventEntryCost: row.eventEntryCost,
  ticketingRequirement: row.ticketingRequirement,
  eventBookingType: row.eventBookingType,
  ticketingVariants: row.ticketingVariants,
  ticketVariantDefinitionBaby: row.ticketVariantDefinitionBaby,
  ticketVariantBabyPrice: row.ticketVariantBabyPrice,
  ticketVariantDefinitionFixedChild: row.ticketVariantDefinitionFixedChild,
  ticketVariantFixedChildPrice: row.ticketVariantFixedChildPrice,
  ticketVariantDefinitionYoungChild: row.ticketVariantDefinitionYoungChild,
  ticketVariantYoungChildPrice: row.ticketVariantYoungChildPrice,
  ticketVariantDefinitionOlderChild: row.ticketVariantDefinitionOlderChild,
  ticketVariantOlderChildPrice: row.ticketVariantOlderChildPrice,
  ticketVariantDefinitionAdult: row.ticketVariantDefinitionAdult,
  ticketVariantAdultPrice: row.ticketVariantAdultPrice,
  ticketVariantDefinitionConcession: row.ticketVariantDefinitionConcession,
  ticketVariantConcessionPrice: row.ticketVariantConcessionPrice,
  ticketVariantDefinitionGroup: row.ticketVariantDefinitionGroup,
  ticketVariantGroupPrice: row.ticketVariantGroupPrice,
  eventParkingProvision: row.eventParkingProvision,
  eventGeneralFacilities: row.eventGeneralFacilities,
  eventChildFacilities: row.eventChildFacilities,
  eventAdultFacilities: row.eventAdultFacilities,
  eventAgeSuitabilityUnder1S: row.eventAgeSuitabilityUnder1S,
  eventAgeSuitability1To2Years: row.eventAgeSuitability1To2Years,
  eventAgeSuitability3To4Years: row.eventAgeSuitability3To4Years,
  eventAgeSuitability5To7Years: row.eventAgeSuitability5To7Years,
  eventAgeSuitability8To12Years: row.eventAgeSuitability8To12Years,
  eventAgeSuitabilityOver13Years: row.eventAgeSuitabilityOver13Years,
  eventAgeSuitabilityAdults: row.eventAgeSuitabilityAdults,
  eventInterestTags: row.eventInterestTags,
  eventSeasonalTags: row.eventSeasonalTags,
  eventSeasonalHighlights: row.eventSeasonalHighlights,
  eventHighlights: row.eventHighlights,
  eventExtraKit: row.eventExtraKit,
  eventSkillArea: row.eventSkillArea,
  eventSkillAreaVariant: row.eventSkillAreaVariant,
  eventAbilityLevel: row.eventAbilityLevel,
  image: row.image,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
  theme: {
    id: row.theme.id,
    slug: row.theme.slug,
    name: row.theme.name,
    recordType: row.theme.recordType,
  },
  themeVariant: {
    id: row.themeVariant.id,
    slug: row.themeVariant.slug,
    name: row.themeVariant.name,
  },
});
