import type { OpportunityVenueV2Response } from "./types.js";

const s = (v: unknown): string | null => (typeof v === "string" && v !== "" ? v : null);
const b = (v: unknown): boolean | null => (typeof v === "boolean" ? v : null);
const n = (v: unknown): number | null => (typeof v === "number" ? v : null);
const d = (v: unknown): Date | null => (v != null ? new Date(v as string) : null);

export function enrichOpportunityVenueV2Response(
  item: Record<string, unknown>,
): OpportunityVenueV2Response {
  const themeSlug = (item.themeSlug as string) ?? "";
  const themeVariantSlug = (item.themeVariantSlug as string) ?? "";
  const oppType = (item.opportunityType as string) ?? "event";

  return {
    id: item.id as string,
    opportunityType: oppType,
    theme: {
      id: themeSlug,
      slug: themeSlug,
      name: themeSlug,
      recordType: oppType,
    },
    themeVariant: {
      id: themeVariantSlug,
      slug: themeVariantSlug,
      name: themeVariantSlug,
    },
    eventName: (item.eventName as string) ?? "",
    eventActivityGroup: s(item.eventActivityGroup),
    eventType: s(item.eventType),
    eventDescription: s(item.eventDescription),
    eventAddressLine1: s(item.eventAddressLine1),
    eventAddressLine2: s(item.eventAddressLine2),
    eventCity: s(item.eventCity),
    eventRegion: s(item.eventRegion),
    eventPostcode: s(item.eventPostcode),
    eventCountry: s(item.eventCountry),
    latitude: s(item.latitude),
    longitude: s(item.longitude),
    eventPhysicalSetting: s(item.eventPhysicalSetting),
    eventDetailedWeatherSuitability: s(item.eventDetailedWeatherSuitability),
    eventStartDate: d(item.eventStartDate),
    eventEndDate: d(item.eventEndDate),
    eventDaysTotal: n(item.eventDaysTotal),
    eventDailyMultiSession: b(item.eventDailyMultiSession),
    eventTimetableWeekly: s(item.eventTimetableWeekly),
    eventDailyFixedTimings: b(item.eventDailyFixedTimings),
    eventDailyFixedStartTime: s(item.eventDailyFixedStartTime),
    eventDailyFixedEndTime: s(item.eventDailyFixedEndTime),
    eventDailyMultiSessionTotal: n(item.eventDailyMultiSessionTotal),
    eventDailyMultiSessionTimings: s(item.eventDailyMultiSessionTimings),
    eventWeeklyFixedStartTime: s(item.eventWeeklyFixedStartTime),
    eventWeeklyFixedEndTime: s(item.eventWeeklyFixedEndTime),
    eventMixedTimingsMondayStart: s(item.eventMixedTimingsMondayStart),
    eventMixedTimingsMondayEnd: s(item.eventMixedTimingsMondayEnd),
    eventMixedTimingsTuesdayStart: s(item.eventMixedTimingsTuesdayStart),
    eventMixedTimingsTuesdayEnd: s(item.eventMixedTimingsTuesdayEnd),
    eventMixedTimingsWednesdayStart: s(item.eventMixedTimingsWednesdayStart),
    eventMixedTimingsWednesdayEnd: s(item.eventMixedTimingsWednesdayEnd),
    eventMixedTimingsThursdayStart: s(item.eventMixedTimingsThursdayStart),
    eventMixedTimingsThursdayEnd: s(item.eventMixedTimingsThursdayEnd),
    eventMixedTimingsFridayStart: s(item.eventMixedTimingsFridayStart),
    eventMixedTimingsFridayEnd: s(item.eventMixedTimingsFridayEnd),
    eventMixedTimingsSaturdayStart: s(item.eventMixedTimingsSaturdayStart),
    eventMixedTimingsSaturdayEnd: s(item.eventMixedTimingsSaturdayEnd),
    eventMixedTimingsSundayStart: s(item.eventMixedTimingsSundayStart),
    eventMixedTimingsSundayEnd: s(item.eventMixedTimingsSundayEnd),
    ticketSalesStartDate: d(item.ticketSalesStartDate),
    eventEntryCost: b(item.eventEntryCost),
    ticketingRequirement: b(item.ticketingRequirement),
    eventBookingType: s(item.eventBookingType),
    ticketingVariants: s(item.ticketingVariants),
    ticketVariantDefinitionBaby: s(item.ticketVariantDefinitionBaby),
    ticketVariantBabyPrice: s(item.ticketVariantBabyPrice),
    ticketVariantDefinitionFixedChild: s(item.ticketVariantDefinitionFixedChild),
    ticketVariantFixedChildPrice: s(item.ticketVariantFixedChildPrice),
    ticketVariantDefinitionYoungChild: s(item.ticketVariantDefinitionYoungChild),
    ticketVariantYoungChildPrice: s(item.ticketVariantYoungChildPrice),
    ticketVariantDefinitionOlderChild: s(item.ticketVariantDefinitionOlderChild),
    ticketVariantOlderChildPrice: s(item.ticketVariantOlderChildPrice),
    ticketVariantDefinitionAdult: s(item.ticketVariantDefinitionAdult),
    ticketVariantAdultPrice: s(item.ticketVariantAdultPrice),
    ticketVariantDefinitionConcession: s(item.ticketVariantDefinitionConcession),
    ticketVariantConcessionPrice: s(item.ticketVariantConcessionPrice),
    ticketVariantDefinitionGroup: s(item.ticketVariantDefinitionGroup),
    ticketVariantGroupPrice: s(item.ticketVariantGroupPrice),
    eventParkingProvision: s(item.eventParkingProvision),
    eventGeneralFacilities: s(item.eventGeneralFacilities),
    eventChildFacilities: s(item.eventChildFacilities),
    eventAdultFacilities: s(item.eventAdultFacilities),
    eventAgeSuitabilityUnder1S: b(item.eventAgeSuitabilityUnder1S),
    eventAgeSuitability1To2Years: b(item.eventAgeSuitability1To2Years),
    eventAgeSuitability3To4Years: b(item.eventAgeSuitability3To4Years),
    eventAgeSuitability5To7Years: b(item.eventAgeSuitability5To7Years),
    eventAgeSuitability8To12Years: b(item.eventAgeSuitability8To12Years),
    eventAgeSuitabilityOver13Years: b(item.eventAgeSuitabilityOver13Years),
    eventAgeSuitabilityAdults: b(item.eventAgeSuitabilityAdults),
    eventInterestTags: s(item.eventInterestTags),
    eventSeasonalTags: s(item.eventSeasonalTags),
    eventSeasonalHighlights: s(item.eventSeasonalHighlights),
    eventHighlights: s(item.eventHighlights),
    eventExtraKit: s(item.eventExtraKit),
    eventSkillArea: s(item.eventSkillArea),
    eventSkillAreaVariant: s(item.eventSkillAreaVariant),
    eventAbilityLevel: s(item.eventAbilityLevel),
    image: s(item.image),
    createdAt: new Date(item.createdAt as string),
    updatedAt: new Date(item.updatedAt as string),
  };
}
