-- Club spreadsheet import (v2 flat columns; theme FKs like opportunity_venue_v2).

CREATE TABLE "opportunity_club_v2" (
    "id" TEXT NOT NULL,
    "opportunity_type" "OpportunityRecordType" NOT NULL DEFAULT 'club',
    "club_opportunity_theme_id" TEXT NOT NULL,
    "club_opportunity_theme_variant_id" TEXT NOT NULL,
    "club_name" TEXT NOT NULL,
    "club_description" TEXT,
    "club_format" TEXT,
    "club_committment" TEXT,
    "club_frequency" TEXT,
    "club_address_line_1" TEXT,
    "club_address_line_2" TEXT,
    "club_city_town" TEXT,
    "club_state_region_province" TEXT,
    "club_postcode" VARCHAR(20),
    "club_country" TEXT,
    "latitude" TEXT,
    "longitude" TEXT,
    "club_start_date" TIMESTAMP(3),
    "club_end_date" TIMESTAMP(3),
    "club_repeat_session" BOOLEAN,
    "club_daily_fixed_session_total" INTEGER,
    "club_daily_fixed_session_schedule" TEXT,
    "club_daily_schedule" TEXT,
    "club_fixed_daily_timings" BOOLEAN,
    "club_daily_start_time" VARCHAR(5),
    "club_daily_end_time" VARCHAR(5),
    "club_mixed_timings_monday_start_time" VARCHAR(5),
    "club_mixed_timings_monday_end_time" VARCHAR(5),
    "club_mixed_timings_tuesday_start_time" VARCHAR(5),
    "club_mixed_timings_tuesday_end_time" VARCHAR(5),
    "club_mixed_timings_wednesday_start_time" VARCHAR(5),
    "club_mixed_timings_wednesday_end_time" VARCHAR(5),
    "club_mixed_timings_thursday_start_time" VARCHAR(5),
    "club_mixed_timings_thursday_end_time" VARCHAR(5),
    "club_mixed_timings_friday_start_time" VARCHAR(5),
    "club_mixed_timings_friday_end_time" VARCHAR(5),
    "club_mixed_timings_saturday_start_time" VARCHAR(5),
    "club_mixed_timings_saturday_end_time" VARCHAR(5),
    "club_mixed_timings_sunday_start_time" VARCHAR(5),
    "club_mixed_timings_sunday_end_time" VARCHAR(5),
    "club_multi_session_monday_session_total" INTEGER,
    "club_multi_session_monday_schedule" TEXT,
    "club_multi_session_tuesday_session_total" INTEGER,
    "club_multi_session_tuesday_schedule" TEXT,
    "club_multi_session_wednesday_session_total" INTEGER,
    "club_multi_session_wednesday_schedule" TEXT,
    "club_multi_session_thursday_session_total" INTEGER,
    "club_multi_session_thursday_schedule" TEXT,
    "club_multi_session_friday_session_total" INTEGER,
    "club_multi_session_friday_schedule" TEXT,
    "club_multi_session_saturday_session_total" INTEGER,
    "club_multi_session_saturday_schedule" TEXT,
    "club_multi_session_sunday_session_total" INTEGER,
    "club_multi_session_sunday_schedule" TEXT,
    "club_monthly_schedule" TEXT,
    "club_fixed_month_occurance" TEXT,
    "club_monthly_occurance" TEXT,
    "club_monthly_fixed_dates" TEXT,
    "ticketing_requirement" BOOLEAN,
    "club_booking_provision" TEXT,
    "ticketing_variants" TEXT,
    "ticket_variant_definition_baby" TEXT,
    "ticket_variant_baby_price" TEXT,
    "ticket_variant_definition__fixed_child" TEXT,
    "ticket_variant_fixed_child_price" TEXT,
    "ticket_variant_definition_young_child" TEXT,
    "ticket_variant_young_child_price" TEXT,
    "ticket_variant_definition_older_child" TEXT,
    "ticket_variant_older_child_price" TEXT,
    "ticket_variant_definition_adult" TEXT,
    "ticket_variant_adult_price" TEXT,
    "ticket_variant_definition_concession" TEXT,
    "ticket_variant_concession_price" TEXT,
    "ticket_variant_definition_group" TEXT,
    "ticket_variant_group_price" TEXT,
    "club_parking_provision" TEXT,
    "club_general_facilities" TEXT,
    "club_child_facilities" TEXT,
    "club_adult_facilities" TEXT,
    "club_age_suitability_under_1_s" BOOLEAN,
    "club_age_suitability_1_to_2_years" BOOLEAN,
    "club_age_suitability_3_to_4_years" BOOLEAN,
    "club_age_suitability_5_to_7_years" BOOLEAN,
    "club_age_suitability_8_to_12_years" BOOLEAN,
    "club_age_suitability_over_13_years" BOOLEAN,
    "club_age_suitability_adults" BOOLEAN,
    "club_activity_group" TEXT,
    "club_physical_setting" TEXT,
    "club_skill_area" TEXT,
    "club_skill_area_variant" TEXT,
    "club_ability_level" TEXT,
    "club_interest_tags" TEXT,
    "club_seasonal_tag" TEXT,
    "club_seasonal_highlights" TEXT,
    "club_attractions" TEXT,
    "club_extra_kit" TEXT,
    "image" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "opportunity_club_v2_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "opportunity_club_v2_club_opportunity_theme_id_idx" ON "opportunity_club_v2"("club_opportunity_theme_id");

CREATE INDEX "opportunity_club_v2_club_opportunity_theme_variant_id_idx" ON "opportunity_club_v2"("club_opportunity_theme_variant_id");

ALTER TABLE "opportunity_club_v2" ADD CONSTRAINT "opportunity_club_v2_club_opportunity_theme_id_fkey" FOREIGN KEY ("club_opportunity_theme_id") REFERENCES "opportunity_theme"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "opportunity_club_v2" ADD CONSTRAINT "opportunity_club_v2_club_opportunity_theme_variant_id_fkey" FOREIGN KEY ("club_opportunity_theme_variant_id") REFERENCES "opportunity_theme_variant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
