import type {
  EnrichableOpportunityRouteV2,
  OpportunityRouteV2Response,
} from "./types.js";

export const enrichOpportunityRouteV2Response = (
  row: EnrichableOpportunityRouteV2,
): OpportunityRouteV2Response => ({
  id: row.id,
  opportunityType: row.opportunityType,
  routeName: row.routeName,
  routeActivityGrouping: row.routeActivityGrouping,
  routeDescription: row.routeDescription,
  routeType: row.routeType,
  routeDistance: row.routeDistance,
  routeTerrainType: row.routeTerrainType,
  routeDifficulty: row.routeDifficulty,
  routeAddressLine1: row.routeAddressLine1,
  routeAddressLine2: row.routeAddressLine2,
  routeRegion: row.routeRegion,
  routePostcode: row.routePostcode,
  latitude: row.latitude,
  longitude: row.longitude,
  routeCountry: row.routeCountry,
  routeParkingProvision: row.routeParkingProvision,
  routeGeneralFacilities: row.routeGeneralFacilities,
  routeChildFacilities: row.routeChildFacilities,
  routeAdultFacilities: row.routeAdultFacilities,
  routeDogFacilities: row.routeDogFacilities,
  routeAgeSuitabilityUnder1S: row.routeAgeSuitabilityUnder1S,
  routeAgeSuitability1To2Years: row.routeAgeSuitability1To2Years,
  routeAgeSuitability3To4Years: row.routeAgeSuitability3To4Years,
  routeAgeSuitability5To7Years: row.routeAgeSuitability5To7Years,
  routeAgeSuitability8To12Years: row.routeAgeSuitability8To12Years,
  routeAgeSuitabilityOver13Years: row.routeAgeSuitabilityOver13Years,
  routeAgeSuitabilityAdults: row.routeAgeSuitabilityAdults,
  routePhysicalSetting: row.routePhysicalSetting,
  routeDetailedWeatherSuitability: row.routeDetailedWeatherSuitability,
  routeEstimatedDuration: row.routeEstimatedDuration,
  routeInterestTags: row.routeInterestTags,
  routeSeasonalTag: row.routeSeasonalTag,
  routeSeasonalHighlights: row.routeSeasonalHighlights,
  routeAttractions: row.routeAttractions,
  routeExtraKit: row.routeExtraKit,
  image: row.image,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
  theme: {
    id: row.theme.id,
    slug: row.theme.slug,
    name: row.theme.name,
    recordType: row.theme.recordType,
  },
  themeVariant: {
    id: row.themeVariant.id,
    slug: row.themeVariant.slug,
    name: row.themeVariant.name,
  },
});
