/** Shared theme/variant refs used across all opportunity types. */
export interface ThemeRef {
  id:         string;
  slug:       string;
  name:       string;
  recordType: string;
}

export interface ThemeVariantRef {
  id:   string;
  slug: string;
  name: string;
}

// ── Venue ─────────────────────────────────────────────────────────────────────

export interface OpportunityVenueV2 {
  id:                               string;
  opportunityType:                  string;
  theme:                            ThemeRef;
  themeVariant:                     ThemeVariantRef;
  venueName:                        string;
  venueActivityGroup:               string | null;
  venueDescription:                 string | null;
  venueAddressLine1:                string | null;
  venueAddressLine2:                string | null;
  venueCity:                        string | null;
  venueRegion:                      string | null;
  venuePostcode:                    string | null;
  latitude:                         string | null;
  longitude:                        string | null;
  venueCountry:                     string | null;
  venueSchedulePattern:             string | null;
  venueFixedDailyTimings:           boolean | null;
  venueFixedTimingsStartTime:       string | null;
  venueFixedTimingsEndTime:         string | null;
  venueMixedTimingsMondayStart:     string | null;
  venueMixedTimingsMondayEnd:       string | null;
  venueMixedTimingsTuesdayStart:    string | null;
  venueMixedTimingsTuesdayEnd:      string | null;
  venueMixedTimingsWednesdayStart:  string | null;
  venueMixedTimingsWednesdayEnd:    string | null;
  venueMixedTimingsThursdayStart:   string | null;
  venueMixedTimingsThursdayEnd:     string | null;
  venueMixedTimingsFridayStart:     string | null;
  venueMixedTimingsFridayEnd:       string | null;
  venueMixedTimingsSaturdayStart:   string | null;
  venueMixedTimingsSaturdayEnd:     string | null;
  venueMixedTimingsSundayStart:     string | null;
  venueMixedTimingsSundayEnd:       string | null;
  venueOpeningExclusions:           string | null;
  venueBankHolidays:                string | null;
  venueEntryCost:                   boolean | null;
  ticketingRequirement:             boolean | null;
  venueBookingType:                 string | null;
  ticketingVariants:                string | null;
  ticketVariantDefinitionBaby:      string | null;
  ticketVariantBabyPrice:           string | null;
  ticketVariantDefinitionFixedChild:   string | null;
  ticketVariantFixedChildPrice:        string | null;
  ticketVariantDefinitionYoungChild:   string | null;
  ticketVariantYoungChildPrice:        string | null;
  ticketVariantDefinitionOlderChild:   string | null;
  ticketVariantOlderChildPrice:        string | null;
  ticketVariantDefinitionAdult:        string | null;
  ticketVariantAdultPrice:             string | null;
  ticketVariantDefinitionConcession:   string | null;
  ticketVariantConcessionPrice:        string | null;
  ticketVariantDefinitionGroup:        string | null;
  ticketVariantGroupPrice:             string | null;
  venueGeneralFacilities:           string | null;
  venueChildFacilities:             string | null;
  venueAdultFacilities:             string | null;
  venueDogFacilities:               string | null;
  venueParkingProvision:            string | null;
  venueAgeSuitabilityUnder1Years:   boolean | null;
  venueAgeSuitability1To2Years:     boolean | null;
  venueAgeSuitability3To4Years:     boolean | null;
  venueAgeSuitability5To7Years:     boolean | null;
  venueAgeSuitability8To12Years:    boolean | null;
  venueAgeSuitabilityOver13Years:   boolean | null;
  venueAgeSuitabilityAdults:        boolean | null;
  venuePhysicalSetting:             string | null;
  venueDetailedWeatherSuitability:  string | null;
  venueEstimatedDuration:           string | null;
  venueInterestTags:                string | null;
  venueSeasonalTag:                 string | null;
  venueSeasonalHighlights:          string | null;
  venueAttractions:                 string | null;
  venueExtraKit:                    string | null;
  image:                            string | null;
  createdAt:                        Date;
  updatedAt:                        Date;
}

// ── Event ─────────────────────────────────────────────────────────────────────

export interface OpportunityEventV2 {
  id:                               string;
  opportunityType:                  string;
  theme:                            ThemeRef;
  themeVariant:                     ThemeVariantRef;
  eventName:                        string;
  eventActivityGroup:               string | null;
  eventType:                        string | null;
  eventDescription:                 string | null;
  eventAddressLine1:                string | null;
  eventAddressLine2:                string | null;
  eventCity:                        string | null;
  eventRegion:                      string | null;
  eventPostcode:                    string | null;
  eventCountry:                     string | null;
  latitude:                         string | null;
  longitude:                        string | null;
  eventPhysicalSetting:             string | null;
  eventDetailedWeatherSuitability:  string | null;
  eventVenueDogFacilities:               string | null;
  eventVenuePhysicalSetting:             string | null;
  eventVenueDetailedWeatherSuitability:  string | null;
  eventVenueEstimatedDuration:           string | null;
  eventStartDate:                   Date | null;
  eventEndDate:                     Date | null;
  eventDaysTotal:                   number | null;
  eventDailyMultiSession:           boolean | null;
  eventTimetableWeekly:             string | null;
  eventDailyFixedTimings:           boolean | null;
  eventDailyFixedStartTime:         string | null;
  eventDailyFixedEndTime:           string | null;
  eventDailyMultiSessionTotal:      number | null;
  eventDailyMultiSessionTimings:    string | null;
  eventWeeklyFixedStartTime:        string | null;
  eventWeeklyFixedEndTime:          string | null;
  eventMixedTimingsMondayStart:     string | null;
  eventMixedTimingsMondayEnd:       string | null;
  eventMixedTimingsTuesdayStart:    string | null;
  eventMixedTimingsTuesdayEnd:      string | null;
  eventMixedTimingsWednesdayStart:  string | null;
  eventMixedTimingsWednesdayEnd:    string | null;
  eventMixedTimingsThursdayStart:   string | null;
  eventMixedTimingsThursdayEnd:     string | null;
  eventMixedTimingsFridayStart:     string | null;
  eventMixedTimingsFridayEnd:       string | null;
  eventMixedTimingsSaturdayStart:   string | null;
  eventMixedTimingsSaturdayEnd:     string | null;
  eventMixedTimingsSundayStart:     string | null;
  eventMixedTimingsSundayEnd:       string | null;
  ticketSalesStartDate:             Date | null;
  eventEntryCost:                   boolean | null;
  ticketingRequirement:             boolean | null;
  eventBookingType:                 string | null;
  ticketingVariants:                string | null;
  ticketVariantDefinitionBaby:      string | null;
  ticketVariantBabyPrice:           string | null;
  ticketVariantDefinitionFixedChild:   string | null;
  ticketVariantFixedChildPrice:        string | null;
  ticketVariantDefinitionYoungChild:   string | null;
  ticketVariantYoungChildPrice:        string | null;
  ticketVariantDefinitionOlderChild:   string | null;
  ticketVariantOlderChildPrice:        string | null;
  ticketVariantDefinitionAdult:        string | null;
  ticketVariantAdultPrice:             string | null;
  ticketVariantDefinitionConcession:   string | null;
  ticketVariantConcessionPrice:        string | null;
  ticketVariantDefinitionGroup:        string | null;
  ticketVariantGroupPrice:             string | null;
  eventParkingProvision:            string | null;
  eventGeneralFacilities:           string | null;
  eventChildFacilities:             string | null;
  eventAdultFacilities:             string | null;
  eventAgeSuitabilityUnder1S:       boolean | null;
  eventAgeSuitability1To2Years:     boolean | null;
  eventAgeSuitability3To4Years:     boolean | null;
  eventAgeSuitability5To7Years:     boolean | null;
  eventAgeSuitability8To12Years:    boolean | null;
  eventAgeSuitabilityOver13Years:   boolean | null;
  eventAgeSuitabilityAdults:        boolean | null;
  eventInterestTags:                string | null;
  eventSeasonalTags:                string | null;
  eventSeasonalHighlights:          string | null;
  eventHighlights:                  string | null;
  eventExtraKit:                    string | null;
  eventSkillArea:                   string | null;
  eventSkillAreaVariant:            string | null;
  eventAbilityLevel:                string | null;
  image:                            string | null;
  createdAt:                        Date;
  updatedAt:                        Date;
}

// ── Club ──────────────────────────────────────────────────────────────────────

export interface OpportunityClubV2 {
  id:                               string;
  opportunityType:                  string;
  theme:                            ThemeRef;
  themeVariant:                     ThemeVariantRef;
  clubName:                         string;
  clubDescription:                  string | null;
  clubFormat:                       string | null;
  clubCommittment:                  string | null;
  clubFrequency:                    string | null;
  clubAddressLine1:                 string | null;
  clubAddressLine2:                 string | null;
  clubCityTown:                     string | null;
  clubStateRegionProvince:          string | null;
  clubPostcode:                     string | null;
  clubCountry:                      string | null;
  latitude:                         string | null;
  longitude:                        string | null;
  clubStartDate:                    Date | null;
  clubEndDate:                      Date | null;
  clubRepeatSession:                boolean | null;
  clubDailyFixedSessionTotal:       number | null;
  clubDailyFixedSessionSchedule:    string | null;
  clubDailySchedule:                string | null;
  clubFixedDailyTimings:            boolean | null;
  clubDailyStartTime:               string | null;
  clubDailyEndTime:                 string | null;
  clubMixedTimingsMondayStartTime:    string | null;
  clubMixedTimingsMondayEndTime:      string | null;
  clubMixedTimingsTuesdayStartTime:   string | null;
  clubMixedTimingsTuesdayEndTime:     string | null;
  clubMixedTimingsWednesdayStartTime: string | null;
  clubMixedTimingsWednesdayEndTime:   string | null;
  clubMixedTimingsThursdayStartTime:  string | null;
  clubMixedTimingsThursdayEndTime:    string | null;
  clubMixedTimingsFridayStartTime:    string | null;
  clubMixedTimingsFridayEndTime:      string | null;
  clubMixedTimingsSaturdayStartTime:  string | null;
  clubMixedTimingsSaturdayEndTime:    string | null;
  clubMixedTimingsSundayStartTime:    string | null;
  clubMixedTimingsSundayEndTime:      string | null;
  clubMultiSessionMondaySessionTotal:    number | null;
  clubMultiSessionMondaySchedule:        string | null;
  clubMultiSessionTuesdaySessionTotal:   number | null;
  clubMultiSessionTuesdaySchedule:       string | null;
  clubMultiSessionWednesdaySessionTotal: number | null;
  clubMultiSessionWednesdaySchedule:     string | null;
  clubMultiSessionThursdaySessionTotal:  number | null;
  clubMultiSessionThursdaySchedule:      string | null;
  clubMultiSessionFridaySessionTotal:    number | null;
  clubMultiSessionFridaySchedule:        string | null;
  clubMultiSessionSaturdaySessionTotal:  number | null;
  clubMultiSessionSaturdaySchedule:      string | null;
  clubMultiSessionSundaySessionTotal:    number | null;
  clubMultiSessionSundaySchedule:        string | null;
  clubMonthlySchedule:              string | null;
  clubFixedMonthOccurance:          string | null;
  clubMonthlyOccurance:             string | null;
  clubMonthlyFixedDates:            string | null;
  ticketingRequirement:             boolean | null;
  clubBookingProvision:             string | null;
  ticketingVariants:                string | null;
  ticketVariantDefinitionBaby:      string | null;
  ticketVariantBabyPrice:           string | null;
  ticketVariantDefinitionFixedChild:   string | null;
  ticketVariantFixedChildPrice:        string | null;
  ticketVariantDefinitionYoungChild:   string | null;
  ticketVariantYoungChildPrice:        string | null;
  ticketVariantDefinitionOlderChild:   string | null;
  ticketVariantOlderChildPrice:        string | null;
  ticketVariantDefinitionAdult:        string | null;
  ticketVariantAdultPrice:             string | null;
  ticketVariantDefinitionConcession:   string | null;
  ticketVariantConcessionPrice:        string | null;
  ticketVariantDefinitionGroup:        string | null;
  ticketVariantGroupPrice:             string | null;
  clubParkingProvision:             string | null;
  clubGeneralFacilities:            string | null;
  clubChildFacilities:              string | null;
  clubAdultFacilities:              string | null;
  clubAgeSuitabilityUnder1S:        boolean | null;
  clubAgeSuitability1To2Years:      boolean | null;
  clubAgeSuitability3To4Years:      boolean | null;
  clubAgeSuitability5To7Years:      boolean | null;
  clubAgeSuitability8To12Years:     boolean | null;
  clubAgeSuitabilityOver13Years:    boolean | null;
  clubAgeSuitabilityAdults:         boolean | null;
  clubActivityGroup:                string | null;
  clubPhysicalSetting:              string | null;
  clubSkillArea:                    string | null;
  clubSkillAreaVariant:             string | null;
  clubAbilityLevel:                 string | null;
  clubInterestTags:                 string | null;
  clubSeasonalTag:                  string | null;
  clubSeasonalHighlights:           string | null;
  clubAttractions:                  string | null;
  clubExtraKit:                     string | null;
  image:                            string | null;
  createdAt:                        Date;
  updatedAt:                        Date;
}

// ── Route ─────────────────────────────────────────────────────────────────────

export interface OpportunityRouteV2 {
  id:                               string;
  opportunityType:                  string;
  theme:                            ThemeRef;
  themeVariant:                     ThemeVariantRef;
  routeName:                        string;
  routeActivityGrouping:            string | null;
  routeDescription:                 string | null;
  routeType:                        string | null;
  routeSuitability:                 string | null;
  routeDistance:                    string | null;
  routeTerrainType:                 string | null;
  routeDifficulty:                  string | null;
  routeAddressLine1:                string | null;
  routeAddressLine2:                string | null;
  routeRegion:                      string | null;
  routePostcode:                    string | null;
  latitude:                         string | null;
  longitude:                        string | null;
  routeCountry:                     string | null;
  routeParkingProvision:            string | null;
  routeGeneralFacilities:           string | null;
  routeChildFacilities:             string | null;
  routeAdultFacilities:             string | null;
  routeDogFacilities:               string | null;
  routeAgeSuitabilityUnder1S:       boolean | null;
  routeAgeSuitability1To2Years:     boolean | null;
  routeAgeSuitability3To4Years:     boolean | null;
  routeAgeSuitability5To7Years:     boolean | null;
  routeAgeSuitability8To12Years:    boolean | null;
  routeAgeSuitabilityOver13Years:   boolean | null;
  routeAgeSuitabilityAdults:        boolean | null;
  routePhysicalSetting:             string | null;
  routeDetailedWeatherSuitability:  string | null;
  routeEstimatedDuration:           string | null;
  routeInterestTags:                string | null;
  routeSeasonalTag:                 string | null;
  routeSeasonalHighlights:          string | null;
  routeAttractions:                 string | null;
  routeExtraKit:                    string | null;
  image:                            string | null;
  createdAt:                        Date;
  updatedAt:                        Date;
}
