import type {
  EnrichableOpportunityVenuesV2,
  OpportunityVenuesV2Response,
} from "./types.js";

export const enrichOpportunityVenuesV2Response = (
  row: EnrichableOpportunityVenuesV2,
): OpportunityVenuesV2Response => ({
  id: row.id,
  opportunityType: row.opportunityType,
  venueName: row.venueName,
  venueActivityGroup: row.venueActivityGroup,
  venueDescription: row.venueDescription,
  venueAddressLine1: row.venueAddressLine1,
  venueAddressLine2: row.venueAddressLine2,
  venueCity: row.venueCity,
  venueRegion: row.venueRegion,
  venuePostcode: row.venuePostcode,
  latitude: row.latitude,
  longitude: row.longitude,
  venueCountry: row.venueCountry,
  venueSchedulePattern: row.venueSchedulePattern,
  venueFixedDailyTimings: row.venueFixedDailyTimings,
  venueFixedTimingsStartTime: row.venueFixedTimingsStartTime,
  venueFixedTimingsEndTime: row.venueFixedTimingsEndTime,
  venueMixedTimingsMondayStart: row.venueMixedTimingsMondayStart,
  venueMixedTimingsMondayEnd: row.venueMixedTimingsMondayEnd,
  venueMixedTimingsTuesdayStart: row.venueMixedTimingsTuesdayStart,
  venueMixedTimingsTuesdayEnd: row.venueMixedTimingsTuesdayEnd,
  venueMixedTimingsWednesdayStart: row.venueMixedTimingsWednesdayStart,
  venueMixedTimingsWednesdayEnd: row.venueMixedTimingsWednesdayEnd,
  venueMixedTimingsThursdayStart: row.venueMixedTimingsThursdayStart,
  venueMixedTimingsThursdayEnd: row.venueMixedTimingsThursdayEnd,
  venueMixedTimingsFridayStart: row.venueMixedTimingsFridayStart,
  venueMixedTimingsFridayEnd: row.venueMixedTimingsFridayEnd,
  venueMixedTimingsSaturdayStart: row.venueMixedTimingsSaturdayStart,
  venueMixedTimingsSaturdayEnd: row.venueMixedTimingsSaturdayEnd,
  venueMixedTimingsSundayStart: row.venueMixedTimingsSundayStart,
  venueMixedTimingsSundayEnd: row.venueMixedTimingsSundayEnd,
  venueEntryCost: row.venueEntryCost,
  ticketingRequirement: row.ticketingRequirement,
  venueBookingType: row.venueBookingType,
  ticketingVariants: row.ticketingVariants,
  ticketVariantDefinitionBaby: row.ticketVariantDefinitionBaby,
  ticketVariantBabyPrice: row.ticketVariantBabyPrice,
  ticketVariantDefinitionFixedChild: row.ticketVariantDefinitionFixedChild,
  ticketVariantFixedChildPrice: row.ticketVariantFixedChildPrice,
  ticketVariantDefinitionYoungChild: row.ticketVariantDefinitionYoungChild,
  ticketVariantYoungChildPrice: row.ticketVariantYoungChildPrice,
  ticketVariantDefinitionOlderChild: row.ticketVariantDefinitionOlderChild,
  ticketVariantOlderChildPrice: row.ticketVariantOlderChildPrice,
  ticketVariantDefinitionAdult: row.ticketVariantDefinitionAdult,
  ticketVariantAdultPrice: row.ticketVariantAdultPrice,
  ticketVariantDefinitionConcession: row.ticketVariantDefinitionConcession,
  ticketVariantConcessionPrice: row.ticketVariantConcessionPrice,
  ticketVariantDefinitionGroup: row.ticketVariantDefinitionGroup,
  ticketVariantGroupPrice: row.ticketVariantGroupPrice,
  venueGeneralFacilities: row.venueGeneralFacilities,
  venueChildFacilities: row.venueChildFacilities,
  venueAdultFacilities: row.venueAdultFacilities,
  venueDogFacilities: row.venueDogFacilities,
  venueParkingProvision: row.venueParkingProvision,
  venueAgeSuitabilityUnder1Years: row.venueAgeSuitabilityUnder1Years,
  venueAgeSuitability1To2Years: row.venueAgeSuitability1To2Years,
  venueAgeSuitability3To4Years: row.venueAgeSuitability3To4Years,
  venueAgeSuitability5To7Years: row.venueAgeSuitability5To7Years,
  venueAgeSuitability8To12Years: row.venueAgeSuitability8To12Years,
  venueAgeSuitabilityOver13Years: row.venueAgeSuitabilityOver13Years,
  venueAgeSuitabilityAdults: row.venueAgeSuitabilityAdults,
  venuePhysicalSetting: row.venuePhysicalSetting,
  venueDetailedWeatherSuitability: row.venueDetailedWeatherSuitability,
  venueEstimatedDuration: row.venueEstimatedDuration,
  venueInterestTags: row.venueInterestTags,
  venueSeasonalTag: row.venueSeasonalTag,
  venueSeasonalHighlights: row.venueSeasonalHighlights,
  venueAttractions: row.venueAttractions,
  venueExtraKit: row.venueExtraKit,
  image: row.image,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
  theme: {
    id: row.theme.id,
    slug: row.theme.slug,
    name: row.theme.name,
    recordType: row.theme.recordType,
  },
  themeVariant: {
    id: row.themeVariant.id,
    slug: row.themeVariant.slug,
    name: row.themeVariant.name,
  },
});
