import type { OpportunityVenuesV2Response } from "./types.js";

const s = (v: unknown): string | null => (typeof v === "string" && v !== "" ? v : null);
const b = (v: unknown): boolean | null => (typeof v === "boolean" ? v : null);

export function enrichOpportunityVenuesV2Response(
  item: Record<string, unknown>,
): OpportunityVenuesV2Response {
  const themeSlug = (item.themeSlug as string) ?? "";
  const themeVariantSlug = (item.themeVariantSlug as string) ?? "";
  const oppType = (item.opportunityType as string) ?? "venue";

  return {
    id: item.id as string,
    opportunityType: oppType,
    theme: {
      id: themeSlug,
      slug: themeSlug,
      name: themeSlug,
      recordType: oppType,
    },
    themeVariant: {
      id: themeVariantSlug,
      slug: themeVariantSlug,
      name: themeVariantSlug,
    },
    venueName: (item.venueName as string) ?? "",
    venueActivityGroup: s(item.venueActivityGroup),
    venueDescription: s(item.venueDescription),
    venueAddressLine1: s(item.venueAddressLine1),
    venueAddressLine2: s(item.venueAddressLine2),
    venueCity: s(item.venueCity),
    venueRegion: s(item.venueRegion),
    venuePostcode: s(item.venuePostcode),
    latitude: s(item.latitude),
    longitude: s(item.longitude),
    venueCountry: s(item.venueCountry),
    venueSchedulePattern: s(item.venueSchedulePattern),
    venueFixedDailyTimings: b(item.venueFixedDailyTimings),
    venueFixedTimingsStartTime: s(item.venueFixedTimingsStartTime),
    venueFixedTimingsEndTime: s(item.venueFixedTimingsEndTime),
    venueMixedTimingsMondayStart: s(item.venueMixedTimingsMondayStart),
    venueMixedTimingsMondayEnd: s(item.venueMixedTimingsMondayEnd),
    venueMixedTimingsTuesdayStart: s(item.venueMixedTimingsTuesdayStart),
    venueMixedTimingsTuesdayEnd: s(item.venueMixedTimingsTuesdayEnd),
    venueMixedTimingsWednesdayStart: s(item.venueMixedTimingsWednesdayStart),
    venueMixedTimingsWednesdayEnd: s(item.venueMixedTimingsWednesdayEnd),
    venueMixedTimingsThursdayStart: s(item.venueMixedTimingsThursdayStart),
    venueMixedTimingsThursdayEnd: s(item.venueMixedTimingsThursdayEnd),
    venueMixedTimingsFridayStart: s(item.venueMixedTimingsFridayStart),
    venueMixedTimingsFridayEnd: s(item.venueMixedTimingsFridayEnd),
    venueMixedTimingsSaturdayStart: s(item.venueMixedTimingsSaturdayStart),
    venueMixedTimingsSaturdayEnd: s(item.venueMixedTimingsSaturdayEnd),
    venueMixedTimingsSundayStart: s(item.venueMixedTimingsSundayStart),
    venueMixedTimingsSundayEnd: s(item.venueMixedTimingsSundayEnd),
    venueEntryCost: b(item.venueEntryCost),
    ticketingRequirement: b(item.ticketingRequirement),
    venueBookingType: s(item.venueBookingType),
    ticketingVariants: s(item.ticketingVariants),
    ticketVariantDefinitionBaby: s(item.ticketVariantDefinitionBaby),
    ticketVariantBabyPrice: s(item.ticketVariantBabyPrice),
    ticketVariantDefinitionFixedChild: s(item.ticketVariantDefinitionFixedChild),
    ticketVariantFixedChildPrice: s(item.ticketVariantFixedChildPrice),
    ticketVariantDefinitionYoungChild: s(item.ticketVariantDefinitionYoungChild),
    ticketVariantYoungChildPrice: s(item.ticketVariantYoungChildPrice),
    ticketVariantDefinitionOlderChild: s(item.ticketVariantDefinitionOlderChild),
    ticketVariantOlderChildPrice: s(item.ticketVariantOlderChildPrice),
    ticketVariantDefinitionAdult: s(item.ticketVariantDefinitionAdult),
    ticketVariantAdultPrice: s(item.ticketVariantAdultPrice),
    ticketVariantDefinitionConcession: s(item.ticketVariantDefinitionConcession),
    ticketVariantConcessionPrice: s(item.ticketVariantConcessionPrice),
    ticketVariantDefinitionGroup: s(item.ticketVariantDefinitionGroup),
    ticketVariantGroupPrice: s(item.ticketVariantGroupPrice),
    venueGeneralFacilities: s(item.venueGeneralFacilities),
    venueChildFacilities: s(item.venueChildFacilities),
    venueAdultFacilities: s(item.venueAdultFacilities),
    venueDogFacilities: s(item.venueDogFacilities),
    venueParkingProvision: s(item.venueParkingProvision),
    venueAgeSuitabilityUnder1Years: b(item.venueAgeSuitabilityUnder1Years),
    venueAgeSuitability1To2Years: b(item.venueAgeSuitability1To2Years),
    venueAgeSuitability3To4Years: b(item.venueAgeSuitability3To4Years),
    venueAgeSuitability5To7Years: b(item.venueAgeSuitability5To7Years),
    venueAgeSuitability8To12Years: b(item.venueAgeSuitability8To12Years),
    venueAgeSuitabilityOver13Years: b(item.venueAgeSuitabilityOver13Years),
    venueAgeSuitabilityAdults: b(item.venueAgeSuitabilityAdults),
    venuePhysicalSetting: s(item.venuePhysicalSetting),
    venueDetailedWeatherSuitability: s(item.venueDetailedWeatherSuitability),
    venueEstimatedDuration: s(item.venueEstimatedDuration),
    venueInterestTags: s(item.venueInterestTags),
    venueSeasonalTag: s(item.venueSeasonalTag),
    venueSeasonalHighlights: s(item.venueSeasonalHighlights),
    venueAttractions: s(item.venueAttractions),
    venueExtraKit: s(item.venueExtraKit),
    image: s(item.image),
    createdAt: new Date(item.createdAt as string),
    updatedAt: new Date(item.updatedAt as string),
  };
}
