export interface OpportunityThemeVariantEntry {
  name: string;
  slug: string;
  relatedEnumNameSlugs?: string[];
  active: boolean;
}

export const OPPORTUNITY_THEME_VARIANT_ENUM: OpportunityThemeVariantEntry[] = [
  { name: "Country Park", slug: "country_parks", relatedEnumNameSlugs: ["green_spaces"], active: true },
  { name: "Parkland or Meadow", slug: "open_parkland", relatedEnumNameSlugs: ["green_spaces"], active: true },
  { name: "Village Green", slug: "village_greens", relatedEnumNameSlugs: ["green_spaces"], active: true },
  { name: "Village Park", slug: "village_parks", relatedEnumNameSlugs: ["green_spaces"], active: true },
  { name: "Urban Green Space", slug: "urban_green_spaces", relatedEnumNameSlugs: ["green_spaces"], active: true },
  { name: "Castle Grounds", slug: "castle_grounds", relatedEnumNameSlugs: ["green_spaces"], active: true },
  { name: "Estate Grounds", slug: "estate_grounds", relatedEnumNameSlugs: ["green_spaces"], active: true },
  { name: "Nature Reserve", slug: "nature_reserves", relatedEnumNameSlugs: ["nature_wildlife"], active: true },
  { name: "Wildlife Hotspot", slug: "wildlife_spotting", relatedEnumNameSlugs: ["nature_wildlife"], active: true },
  { name: "Hydes or Cabins", slug: "hydes_cabins", relatedEnumNameSlugs: ["nature_wildlife"], active: true },
  { name: "Information Hut or Learning Centre", slug: "learning_hut", relatedEnumNameSlugs: ["nature_wildlife"], active: true },
  { name: "Forest School", slug: "forest_school", relatedEnumNameSlugs: ["nature_wildlife"], active: true },
  { name: "Natural Play Area", slug: "natural_play_areas", relatedEnumNameSlugs: ["nature_wildlife"], active: true },
  { name: "Den-Building & Nature Craft", slug: "den_building", relatedEnumNameSlugs: ["nature_wildlife"], active: true },
  { name: "Discovery Trail", slug: "nature_trails", relatedEnumNameSlugs: ["nature_wildlife"], active: true },
  { name: "Sandy Beach", slug: "sandy_beach", relatedEnumNameSlugs: ["coastal_adventures"], active: true },
  { name: "Pebble or Shingle Beach", slug: "pebble_beach", relatedEnumNameSlugs: ["coastal_adventures"], active: true },
  { name: "RNLI Beach", slug: "rnli_beach", relatedEnumNameSlugs: ["coastal_adventures"], active: true },
  { name: "Rocky Cove", slug: "coves_exploration", relatedEnumNameSlugs: ["coastal_adventures"], active: true },
  { name: "Coasteering Beach", slug: "coasteering_adventure", relatedEnumNameSlugs: ["coastal_adventures"], active: true },
  { name: "Wild or Remote Beach", slug: "wild_open_beaches", relatedEnumNameSlugs: ["coastal_adventures"], active: true },
  { name: "Dog-Friendly Beach", slug: "dog_friendly_beaches", relatedEnumNameSlugs: ["coastal_adventures"], active: true },
  { name: "Mixed Sand & Shingle Beach", slug: "mixed_sand_shingle", relatedEnumNameSlugs: ["coastal_adventures"], active: true },
  { name: "Sheltered Cove or Bay", slug: "cove_or_bay", relatedEnumNameSlugs: ["coastal_adventures"], active: true },
  { name: "Surf Beach", slug: "surf_beach", relatedEnumNameSlugs: ["coastal_adventures"], active: true },
  { name: "Harbour or Village Beach", slug: "harbour_beach", relatedEnumNameSlugs: ["coastal_adventures"], active: true },
  { name: "Estuary Beach", slug: "estuary_beach", relatedEnumNameSlugs: ["coastal_adventures"], active: true },
  { name: "Botanical Garden", slug: "botanical_gardens", relatedEnumNameSlugs: ["gardens_outdoor"], active: true },
  { name: "Arboretum", slug: "arboretum", relatedEnumNameSlugs: ["gardens_outdoor"], active: true },
  { name: "Historic Estate Garden", slug: "historic_estate_gardens", relatedEnumNameSlugs: ["gardens_outdoor"], active: true },
  { name: "Landscaped Garden", slug: "formal_landscape_gardens", relatedEnumNameSlugs: ["gardens_outdoor"], active: true },
  { name: "Community Garden", slug: "community_gardens", relatedEnumNameSlugs: ["gardens_outdoor"], active: true },
  { name: "Themed Garden", slug: "themed_gardens", relatedEnumNameSlugs: ["gardens_outdoor"], active: true },
  { name: "Enclosed Garden", slug: "enclosed_gardens", relatedEnumNameSlugs: ["gardens_outdoor"], active: true },
  { name: "Destination Playground", slug: "large_playgrounds", relatedEnumNameSlugs: ["active_play"], active: true },
  { name: "Local park", slug: "local_playgrouns", relatedEnumNameSlugs: ["active_play"], active: true },
  { name: "Adventure Playground", slug: "adventure_playgrounds", relatedEnumNameSlugs: ["active_play"], active: true },
  { name: "Natural Obstacle Course", slug: "natural_play", relatedEnumNameSlugs: ["active_play"], active: true },
  { name: "Skate Park", slug: "skate_park", relatedEnumNameSlugs: ["active_play"], active: true },
  { name: "Orienteering Course", slug: "orienteering_course", relatedEnumNameSlugs: ["active_play"], active: true },
  { name: "Letterboxing Site", slug: "letterboxing_course", relatedEnumNameSlugs: ["active_play"], active: true },
  { name: "Leisure Centre", slug: "leisure_centre", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Adventure / Assault Course", slug: "assault_course", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Climbing Centre", slug: "climbing_centre", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Multisports Centre", slug: "multisports_activity_centre", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Sport Stadium", slug: "sports_stadium", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Sport Arena", slug: "sports_arena", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Swimming Pool", slug: "swimming_pool", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Community Centre", slug: "community_centre", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Range", slug: "range", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Sports Track", slug: "sports_track", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Indoor Court", slug: "indoor_courts", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Outdoor Court", slug: "outdoor_courts", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Specialist Facility", slug: "specialist_sports_facility", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Outdoor Pitch", slug: "outdoor_pitch", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Gym", slug: "gym", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Coached Sessions", slug: "coached_sessions", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Structured Lessons", slug: "structured_lessons", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Club or Team", slug: "clubs_and_teams", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Training or Skills Focus", slug: "training_and_drills", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Kit & Equipment Hire", slug: "kit_hire", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Hireable Court/Pitch", slug: "hire_and_free_practice", relatedEnumNameSlugs: ["sporty_activities"], active: true },
  { name: "Winter Wonderland", slug: "winter_wonderland", relatedEnumNameSlugs: ["seasonal"], active: true },
  { name: "Ice-skating Rink", slug: "ice_rink", relatedEnumNameSlugs: ["seasonal"], active: true },
  { name: "Festival Park", slug: "festival_park", relatedEnumNameSlugs: ["seasonal"], active: true },
  { name: "Arena", slug: "arena", relatedEnumNameSlugs: ["seasonal"], active: true },
  { name: "Stadium", slug: "statium", relatedEnumNameSlugs: ["seasonal"], active: true },
  { name: "Showground", slug: "showground", relatedEnumNameSlugs: ["seasonal"], active: true },
  { name: "Fairground", slug: "fairground", relatedEnumNameSlugs: ["seasonal"], active: true },
  { name: "PYO Farm", slug: "pick_your_own", relatedEnumNameSlugs: ["seasonal"], active: true },
  { name: "Lights Trail", slug: "light_trail", relatedEnumNameSlugs: ["seasonal"], active: true },
  { name: "Patch or Field", slug: "patch", relatedEnumNameSlugs: ["seasonal"], active: true },
  { name: "Paddle Spot", slug: "paddle_spot", relatedEnumNameSlugs: ["water_fun"], active: true },
  { name: "Water play", slug: "water_play", relatedEnumNameSlugs: ["water_fun"], active: true },
  { name: "River Beach", slug: "river_beach", relatedEnumNameSlugs: ["water_fun"], active: true },
  { name: "Waterparks", slug: "water_park", relatedEnumNameSlugs: ["water_fun"], active: true },
  { name: "On The Water", slug: "water_rides", relatedEnumNameSlugs: ["water_fun"], active: true },
  { name: "Water Adventure", slug: "water_adventure", relatedEnumNameSlugs: ["water_fun"], active: true },
  { name: "Creative Artwork", slug: "making_and_creating", relatedEnumNameSlugs: ["creative_play"], active: true },
  { name: "Music & Movement", slug: "expressive_movement_and_music", relatedEnumNameSlugs: ["creative_play"], active: true },
  { name: "Creative Expression", slug: "creative_expression", relatedEnumNameSlugs: ["creative_play"], active: true },
  { name: "Performative Arts", slug: "performing_and_putting_on_a_show", relatedEnumNameSlugs: ["creative_play"], active: true },
  { name: "Film or Media", slug: "film_photography", relatedEnumNameSlugs: ["creative_play"], active: true },
  { name: "Character-Led Play", slug: "role_play_and_characters", relatedEnumNameSlugs: ["imaginative_play"], active: true },
  { name: "Immersive Worlds", slug: "immersive_worlds", relatedEnumNameSlugs: ["imaginative_play"], active: true },
  { name: "Scenario & World play", slug: "scenario_and_world_play", relatedEnumNameSlugs: ["imaginative_play"], active: true },
  { name: "Narrative-led experiences", slug: "narrative_led_experiences", relatedEnumNameSlugs: ["imaginative_play"], active: true },
  { name: "Sensory garden", slug: "sensory_garden", relatedEnumNameSlugs: ["sensory_soothing"], active: true },
  { name: "Sensory Space", slug: "sensory_room_or_space", relatedEnumNameSlugs: ["sensory_soothing"], active: true },
  { name: "Soothing Environment", slug: "calming_designed_environment", relatedEnumNameSlugs: ["sensory_soothing"], active: true },
  { name: "Light-touch Sensory", slug: "light_touch_sensory_experience", relatedEnumNameSlugs: ["sensory_soothing"], active: true },
  { name: "Experiments", slug: "experiments", relatedEnumNameSlugs: ["hands_on_learning"], active: true },
  { name: "Discovery-Based Challenges", slug: "discovery_challenges", relatedEnumNameSlugs: ["hands_on_learning"], active: true },
  { name: "Learning Through Play", slug: "learning_through_play", relatedEnumNameSlugs: ["hands_on_learning"], active: true },
  { name: "Interactive Exhibits", slug: "interactive_exhibits", relatedEnumNameSlugs: ["hands_on_learning"], active: true },
  { name: "Problem-Solving", slug: "problem_solving", relatedEnumNameSlugs: ["hands_on_learning"], active: true },
  { name: "Construction Activities", slug: "construction_activity", relatedEnumNameSlugs: ["hands_on_learning"], active: true },
  { name: "Science & Discovery", slug: "science_and_discovery", relatedEnumNameSlugs: ["interactive_museums"], active: true },
  { name: "Technology & Innovation", slug: "technology_and_innovation", relatedEnumNameSlugs: ["interactive_museums"], active: true },
  { name: "History & Pastimes", slug: "history_made_interactive", relatedEnumNameSlugs: ["interactive_museums"], active: true },
  { name: "World & Cultures", slug: "world_and_cultures", relatedEnumNameSlugs: ["interactive_museums"], active: true },
  { name: "Child-Focused Discovery", slug: "children_focused_discovery", relatedEnumNameSlugs: ["interactive_museums"], active: true },
  { name: "Farm or Smallholding", slug: "farm_and_smallholding", relatedEnumNameSlugs: ["animal_encounters"], active: true },
  { name: "Wildlife Reserve", slug: "wildlife_reserve", relatedEnumNameSlugs: ["animal_encounters"], active: true },
  { name: "Animal Parks & Zoos", slug: "animal_parks", relatedEnumNameSlugs: ["animal_encounters"], active: true },
  { name: "Conservation Project", slug: "conservation_project", relatedEnumNameSlugs: ["animal_encounters"], active: true },
  { name: "Animal Sanctuary", slug: "animal_sanctuary", relatedEnumNameSlugs: ["animal_encounters"], active: true },
  { name: "Marine Aquarium", slug: "sealife_aquarium", relatedEnumNameSlugs: ["animal_encounters"], active: true },
  { name: "Reptiles & Exotics", slug: "reptiles_and_exotics", relatedEnumNameSlugs: ["animal_encounters"], active: true },
  { name: "Bird of Prey Centre", slug: "birds_of_prey", relatedEnumNameSlugs: ["animal_encounters"], active: true },
  { name: "Stables or Yard", slug: "stables_yard", relatedEnumNameSlugs: ["animal_encounters"], active: true },
  { name: "Ancient Site", slug: "ancient_sites", relatedEnumNameSlugs: ["historical_cultural"], active: true },
  { name: "Historic Estate", slug: "historic_houses", relatedEnumNameSlugs: ["historical_cultural"], active: true },
  { name: "Living History", slug: "living_history", relatedEnumNameSlugs: ["historical_cultural"], active: true },
  { name: "Open-Air Museum", slug: "open_museum", relatedEnumNameSlugs: ["historical_cultural"], active: true },
  { name: "Industrial & Working History", slug: "industrial_history", relatedEnumNameSlugs: ["historical_cultural"], active: true },
  { name: "Archaeological", slug: "archaeological_sites", relatedEnumNameSlugs: ["historical_cultural"], active: true },
  { name: "Cultural Heritage Site", slug: "cultural_heritage", relatedEnumNameSlugs: ["historical_cultural"], active: true },
  { name: "Historic Religious Building", slug: "historic_religious", relatedEnumNameSlugs: ["historical_cultural"], active: true },
  { name: "Soft Play Centre", slug: "large_soft_play", relatedEnumNameSlugs: ["soft_play"], active: true },
  { name: "Toddler Play Space", slug: "toddler_soft_play", relatedEnumNameSlugs: ["soft_play"], active: true },
  { name: "Indoor Climbing", slug: "indoor_climbing", relatedEnumNameSlugs: ["soft_play"], active: true },
  { name: "Inside Course", slug: "indoor_course", relatedEnumNameSlugs: ["soft_play"], active: true },
  { name: "Trampoline Park", slug: "trampoline_park", relatedEnumNameSlugs: ["soft_play"], active: true },
  { name: "Multi-Activity Centre", slug: "indoor_multi_activity", relatedEnumNameSlugs: ["soft_play"], active: true },
  { name: "Cinema", slug: "cinema", relatedEnumNameSlugs: ["indoor_entertainment"], active: true },
  { name: "Stage-Show", slug: "theature_panto", relatedEnumNameSlugs: ["indoor_entertainment"], active: true },
  { name: "Live Events", slug: "live_events", relatedEnumNameSlugs: ["indoor_entertainment"], active: true },
  { name: "Gaming & VR", slug: "gaming", relatedEnumNameSlugs: ["indoor_entertainment"], active: true },
  { name: "Escape Room", slug: "escape_room", relatedEnumNameSlugs: ["indoor_entertainment"], active: true },
  { name: "Improvised Performance", slug: "improvised_performance", relatedEnumNameSlugs: ["indoor_entertainment"], active: true },
  { name: "Comedy", slug: "comedy_club", relatedEnumNameSlugs: ["indoor_entertainment"], active: true },
  { name: "Karaoke", slug: "karaoke_club", relatedEnumNameSlugs: ["indoor_entertainment"], active: true },
  { name: "Arcade / Amusements", slug: "arcade_hall", relatedEnumNameSlugs: ["indoor_entertainment"], active: true },
  { name: "Laser Tag", slug: "laser_tag", relatedEnumNameSlugs: ["indoor_entertainment"], active: true },
  { name: "Bowling", slug: "bowling_alley", relatedEnumNameSlugs: ["indoor_entertainment"], active: true },
  { name: "Trains & Railways", slug: "trains_and_rail", relatedEnumNameSlugs: ["vehicles_transport"], active: true },
  { name: "Boat Trips & Ferries", slug: "boat_trips", relatedEnumNameSlugs: ["vehicles_transport"], active: true },
  { name: "Harbours & Marinas", slug: "harbours_and_marinas", relatedEnumNameSlugs: ["vehicles_transport"], active: true },
  { name: "Aircraft & Aviation", slug: "aviation_experiences", relatedEnumNameSlugs: ["vehicles_transport"], active: true },
  { name: "Transport Museum", slug: "transport_museums", relatedEnumNameSlugs: ["vehicles_transport"], active: true },
  { name: "Working Transport Hubs", slug: "working_transport_hubs", relatedEnumNameSlugs: ["vehicles_transport"], active: true },
  { name: "Themepark", slug: "themepark", relatedEnumNameSlugs: ["big_day_out"], active: true },
  { name: "Amusement Park", slug: "amusement_park", relatedEnumNameSlugs: ["big_day_out"], active: true },
  { name: "Major Animal Attractions", slug: "major_animal_attractions", relatedEnumNameSlugs: ["big_day_out"], active: true },
  { name: "Large-Scale Outdoor Attractions", slug: "large_scale_outdoor", relatedEnumNameSlugs: ["big_day_out"], active: true },
  { name: "Major Indoor Attractions", slug: "major_indoor", relatedEnumNameSlugs: ["big_day_out"], active: true },
  { name: "Seasonal & Themed Events", slug: "seasonal_and_themed", relatedEnumNameSlugs: ["big_day_out"], active: true },
  { name: "Family-Friendly Cafés", slug: "family_friendly_cafes", relatedEnumNameSlugs: ["relaxed_cafe"], active: true },
  { name: "Quiet Cafés", slug: "cafe_with_play", relatedEnumNameSlugs: ["relaxed_cafe"], active: true },
  { name: "Cafés with Outdoor Space", slug: "cafe_with_outdoor_space", relatedEnumNameSlugs: ["relaxed_cafe"], active: true },
  { name: "Coffee Cabin / Truck", slug: "coffee_cabin", relatedEnumNameSlugs: ["relaxed_cafe"], active: true },
  { name: "Easy Pit-Stops", slug: "pit_stop_cafes", relatedEnumNameSlugs: ["relaxed_cafe"], active: true },
  { name: "Family Eateries", slug: "casual_family_restaurants", relatedEnumNameSlugs: ["family_dining"], active: true },
  { name: "Outdoor Family Dining", slug: "dining_with_space", relatedEnumNameSlugs: ["family_dining"], active: true },
  { name: "Destination Family Dining", slug: "destination_dining", relatedEnumNameSlugs: ["family_dining"], active: true },
  { name: "Food Festivals", slug: "food_festival", relatedEnumNameSlugs: ["family_dining"], active: true },
  { name: "Woodland Walk", slug: "woodland_walk", relatedEnumNameSlugs: ["scenic_walks"], active: true },
  { name: "Coastal or Clifftop Walk", slug: "coastal_walk", relatedEnumNameSlugs: ["scenic_walks"], active: true },
  { name: "River or Lakeside Ramble", slug: "riverside_walk", relatedEnumNameSlugs: ["scenic_walks"], active: true },
  { name: "Nature Trail", slug: "nature_trail", relatedEnumNameSlugs: ["scenic_walks"], active: true },
  { name: "National Park", slug: "national_park", relatedEnumNameSlugs: ["scenic_walks"], active: true },
  { name: "Waymarked Trail", slug: "waymarked_trail", relatedEnumNameSlugs: ["scenic_walks"], active: true },
  { name: "Estate Grounds", slug: "estate_grounds_scenic_walks_trails", relatedEnumNameSlugs: ["scenic_walks"], active: true },
  { name: "Heathland", slug: "heathland", relatedEnumNameSlugs: ["scenic_walks"], active: true },
  { name: "Feature Walk", slug: "feature_walk", relatedEnumNameSlugs: ["scenic_walks"], active: true },
  { name: "Local Wander", slug: "gentle_wander", relatedEnumNameSlugs: ["scenic_walks"], active: true },
  { name: "Challenging Hike", slug: "hilly_hike", relatedEnumNameSlugs: ["scenic_walks"], active: true },
  { name: "City Circuit", slug: "city_circuit", relatedEnumNameSlugs: ["scenic_walks"], active: true },
  { name: "Towpath", slug: "towpaths", relatedEnumNameSlugs: ["scenic_walks"], active: true },
  { name: "Quick spin", slug: "quick_spin", relatedEnumNameSlugs: ["wheels_routes"], active: true },
  { name: "Longer ride", slug: "longer_ride", relatedEnumNameSlugs: ["wheels_routes"], active: true },
  { name: "Practise Space", slug: "practise_route", relatedEnumNameSlugs: ["wheels_routes"], active: true },
  { name: "Skills & Stunts Space", slug: "skills_and_stunts", relatedEnumNameSlugs: ["wheels_routes"], active: true },
];

export type OpportunityThemeVariantSlug = (typeof OPPORTUNITY_THEME_VARIANT_ENUM)[number]["slug"];
