import type { OpportunityVenueV2SeedInput } from "../create_opportunity_venue_v2.js";

export const extonChildrensPlayAreaVenueV2: OpportunityVenueV2SeedInput = {
  themeSlug: "playgrounds_and_adventure_play",
  themeVariantSlug: "local_playgrounds",
  venueName: "Exton Children's Play Area",
  venueActivityGroup: "Simple Reset, Energy Burner, Low Effort",
  venueDescription:
    "A small well-maintained village play park situated alongside the beautiful Exe Estuary area, a stone's throw from the Exe Estuary Trail and Exton Train Station, making it ideal for a quick pitstop on a bike ride, or an easy destination to combine with a scenic walk or train ride. ",
  venueAddressLine1: "Long View",
  venueAddressLine2: "Station Road",
  venueCity: "Exton",
  venueRegion: "Devon",
  venuePostcode: "EX3 0TR",
  latitude: "50.668108",
  longitude: "-3.44235",
  venueCountry: null,
  venueSchedulePattern:
    "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday",
  venueFixedDailyTimings: true,
  venueFixedTimingsStartTime: "12:00",
  venueFixedTimingsEndTime: "12:00",
  venueEntryCost: false,
  ticketingRequirement: false,
  venueBookingType: "Open (Free) Access",
  ticketingVariants: null,
  ticketVariantDefinitionBaby: "-",
  ticketVariantBabyPrice: "£0.00",
  ticketVariantDefinitionFixedChild: "-",
  ticketVariantFixedChildPrice: "£0.00",
  ticketVariantDefinitionYoungChild: "-",
  ticketVariantYoungChildPrice: "£0.00",
  ticketVariantDefinitionOlderChild: "-",
  ticketVariantOlderChildPrice: "£0.00",
  ticketVariantDefinitionAdult: "-",
  ticketVariantAdultPrice: "£0.00",
  ticketVariantDefinitionConcession: "-",
  ticketVariantConcessionPrice: "£0.00",
  ticketVariantDefinitionGroup: "-",
  ticketVariantGroupPrice: "£0.00",
  venueParkingProvision: "On-street / nearby parking",
  venueGeneralFacilities: "Bench Seating, Picnic Benches",
  venueChildFacilities:
    "Swings, Slides, Climbing Frames, Zip Line, Outdoor play equipment",
  venueAdultFacilities: "Clear Sightlines",
  venueDogFacilities: null,
  venueAgeSuitabilityUnder1Years: false,
  venueAgeSuitability1To2Years: true,
  venueAgeSuitability3To4Years: true,
  venueAgeSuitability5To7Years: true,
  venueAgeSuitability8To12Years: true,
  venueAgeSuitabilityOver13Years: false,
  venueAgeSuitabilityAdults: false,
  venuePhysicalSetting: "Outside",
  venueDetailedWeatherSuitability:
    "Sunshine, Overcast / cloudy, Dry & mild, Dry & cold, Dry & warm, Dry & hot",
  venueEstimatedDuration: "30-60mins",
  venueInterestTags:
    "zip line, swings, apple trees, slide, football field",
  venueSeasonalTag: null,
  venueSeasonalHighlights: "Fruit Picking",
  venueAttractions:
    "Zip wires, Fireman's poles, Tunnels and crawl spaces, Balance elements, Climbing frames",
  venueExtraKit: null,
  image: "Exton Children's Play Area.JPG",
};
