import type { OpportunityVenueV2SeedInput } from "../create_opportunity_venue_v2.js";

export const theHamPlayParkVenueV2: OpportunityVenueV2SeedInput = {
  themeSlug: "playgrounds_and_adventure_play",
  themeVariantSlug: "local_playgrounds",
  venueName: "The Ham Play Park",
  venueActivityGroup: "Simple Reset, Energy Burner, Low Effort",
  venueDescription:
    "Tucked behind Sidmouth Leisure Centre, this well-known local spot boasts a large sandpit stocked with community sand toys, a variety of play equipment and sits a short distance from the bustle of Sidmouth's highstreet, coffee shops and amenities. With views of the surrounding cliffs and pebble beach, it offers a quieter alternative to the beach with lots to keep younger children busy.",
  venueAddressLine1: "Ham Play Park",
  venueAddressLine2: null,
  venueCity: "Sidmouth",
  venueRegion: "Devon",
  venuePostcode: "EX10 8BP",
  latitude: "50.679961",
  longitude: "-3.235504",
  venueCountry: null,
  venueSchedulePattern:
    "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday",
  venueFixedDailyTimings: true,
  venueFixedTimingsStartTime: "12:00",
  venueFixedTimingsEndTime: "12:00",
  venueEntryCost: false,
  ticketingRequirement: false,
  venueBookingType: "Open (Free) Access",
  ticketingVariants: null,
  ticketVariantDefinitionBaby: "-",
  ticketVariantBabyPrice: "£0.00",
  ticketVariantDefinitionFixedChild: "-",
  ticketVariantFixedChildPrice: "£0.00",
  ticketVariantDefinitionYoungChild: "-",
  ticketVariantYoungChildPrice: "£0.00",
  ticketVariantDefinitionOlderChild: "-",
  ticketVariantOlderChildPrice: "£0.00",
  ticketVariantDefinitionAdult: "-",
  ticketVariantAdultPrice: "£0.00",
  ticketVariantDefinitionConcession: "-",
  ticketVariantConcessionPrice: "£0.00",
  ticketVariantDefinitionGroup: "-",
  ticketVariantGroupPrice: "£0.00",
  venueParkingProvision: "Paid Car Park",
  venueGeneralFacilities: "Bench Seating",
  venueChildFacilities:
    "Sandpit, Zip Line, Outdoor play equipment",
  venueAdultFacilities: null,
  venueDogFacilities: null,
  venueAgeSuitabilityUnder1Years: false,
  venueAgeSuitability1To2Years: true,
  venueAgeSuitability3To4Years: true,
  venueAgeSuitability5To7Years: true,
  venueAgeSuitability8To12Years: true,
  venueAgeSuitabilityOver13Years: false,
  venueAgeSuitabilityAdults: false,
  venuePhysicalSetting: "Outside",
  venueDetailedWeatherSuitability:
    "Sunshine, Overcast / cloudy, Dry & mild, Dry & cold, Dry & warm, Dry & hot",
  venueEstimatedDuration: "30-60mins",
  venueInterestTags:
    "sandpit, sandtoys, climbing wall, zip line, slide, swings, pirate ship",
  venueSeasonalTag: null,
  venueSeasonalHighlights: null,
  venueAttractions:
    "Balance elements, Slides (particularly tall or long), Climbing Wall, Zip wires",
  venueExtraKit: "Sand toys",
  image: "The Ham Play Park.JPG",
};
