import type { OpportunityClubV2SeedInput } from "./create_opportunity_club_v2_row.js";

function d(s: string): Date {
  const [dd, mm, yyyy] = s.split("/").map((x) => Number(x.trim()));
  return new Date(yyyy, mm - 1, dd);
}

/** Demo club v2 import rows (Exmouth / Exeter area); theme slugs match `seed_opportunity_themes.ts`. */
export const opportunityClubV2SeedRows: OpportunityClubV2SeedInput[] = [
  {
    opportunityType: "club",
    themeSlug: "nature_and_wildlife_exploration",
    themeVariantSlug: "forest_school",
    clubName: "Twig-lits Forest School",
    clubDescription:
      "Twig-lits takes place in a meandering Forest school setting, tucked away in the forests of Aylesbere with lots of thoughtfully considered areas that children the chance to build confidence and curiosity in a beautiful outdoor space. With a variety of different stations, there's something for a wide range of ages. The incredibly friendly instructors guide each session in an intentional and considered manner, and the attention to detail elevates this into a magical experience for kids.",
    clubFormat: "Stay-and-play (supervised)",
    clubCommittment: "One-off (pay as you go)",
    clubFrequency: "Weekly",
    clubAddressLine1: "Twiglits Forest School",
    clubAddressLine2: "Venn Ottery",
    clubPostcode: "EX11 1SG",
    latitude: "50.7158",
    longitude: "-3.331",
    clubStartDate: d("01/01/2026"),
    clubRepeatSession: false,
    clubDailySchedule: "Friday, Thursday, Tuesday",
    clubFixedDailyTimings: true,
    clubDailyStartTime: "11:00",
    clubDailyEndTime: "12:00",
    ticketingRequirement: true,
    clubBookingProvision: "Advance Book, Pre-Register",
    ticketingVariants: "(Fixed) Child",
    ticketVariantDefinitionFixedChild: "(Fixed) Child",
    ticketVariantDefinitionYoungChild: "2-13",
    ticketVariantYoungChildPrice: "£9.00",
    clubParkingProvision: "Free Car Park",
    clubGeneralFacilities: "Toilets, Bench Seating",
    clubChildFacilities: "Activity sheets, Activity trail, Clues / games",
    clubAdultFacilities: "Hot Drinks, Log burner",
    clubAgeSuitabilityUnder1S: false,
    clubAgeSuitability1To2Years: false,
    clubAgeSuitability3To4Years: true,
    clubAgeSuitability5To7Years: true,
    clubAgeSuitability8To12Years: false,
    clubAgeSuitabilityOver13Years: false,
    clubAgeSuitabilityAdults: true,
    clubActivityGroup: "Simple Reset",
    clubPhysicalSetting: "Outside",
    clubSkillArea: "Outdoors & Nature",
    clubAbilityLevel: "None / Novice",
    clubInterestTags:
      "Den building, bug-hunting, wildlife spotting, bird calls, bushcraft, craft, nature-based toys, rope swings, mud kitchen, wildlife pond, marshmallow toasting",
    clubSeasonalTag: "Autumn colours",
    clubSeasonalHighlights:
      "Birdsong, Butterflies, Wildflower Meadows, Fungi, \"Berries, Nuts, Conkers\"",
    clubAttractions:
      "Mud kitchens, \"Sand, soil, and loose materials\", Den-building materials, Natural construction zones, Forest school activities, Guided outdoor learning prompts, Marked Trails, Immersive natural surroundings, Quiet or low-intervention spaces",
    clubExtraKit:
      "Wellies, Sturdy footwear, Binoculars, Sling / baby carrier, Infant / toddler carrier, XC Buggy",
    image: "Twiglits Forest School.JPG",
  },
  {
    opportunityType: "club",
    themeSlug: "sporty_activities",
    themeVariantSlug: "climbing_centre",
    clubName: "Youth Climbing Club",
    clubDescription:
      "The Youth Climbing Club is designed for young adults who want to develop existing climbing skills and progress through the National Indoor Climbing Award Scheme. You can expect exiting and challenging sessions from experienced climbing instructors in a group that is sure to refine technique and confidence.",
    clubFormat: "Training / Skill Development",
    clubCommittment: "Monthly",
    clubFrequency: "Weekly",
    clubAddressLine1: "The Quay Climbing Centre",
    clubAddressLine2: "Haven Road",
    clubCityTown: "Exeter",
    clubPostcode: "EX2 8AX",
    latitude: "50.7066",
    longitude: "-3.5007",
    clubStartDate: d("01/01/2026"),
    clubRepeatSession: true,
    clubDailySchedule:
      "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday",
    clubFixedDailyTimings: false,
    clubMixedTimingsMondayStartTime: "17:00",
    clubMixedTimingsMondayEndTime: "18:30",
    clubMixedTimingsTuesdayStartTime: "17:00",
    clubMixedTimingsTuesdayEndTime: "18:30",
    clubMixedTimingsWednesdayStartTime: "17:00",
    clubMixedTimingsWednesdayEndTime: "18:30",
    clubMixedTimingsThursdayStartTime: "17:00",
    clubMixedTimingsThursdayEndTime: "18:30",
    clubMixedTimingsFridayStartTime: "17:00",
    clubMixedTimingsFridayEndTime: "18:30",
    clubMultiSessionMondaySessionTotal: 3,
    clubMultiSessionMondaySchedule:
      "09:15-10:45, 11:00-12:30, 18:00-19:30",
    clubMultiSessionTuesdaySessionTotal: 2,
    clubMultiSessionTuesdaySchedule: "09:15-10:45, 11:00-12:30",
    ticketingRequirement: true,
    clubBookingProvision: "Pre-Register, Advance Book, Members Only",
    ticketingVariants: "Older Child",
    ticketVariantDefinitionOlderChild: "Older Child",
    ticketVariantDefinitionAdult: "11-17",
    ticketVariantAdultPrice: "£36.00",
    clubParkingProvision: "Paid Car Park, On-street / nearby parking",
    clubGeneralFacilities:
      "Toilets, Showers / changing facilities, Indoor Seating",
    clubAdultFacilities:
      "Hot Drinks, Comfy Seating / Sofas, Hot & Cold food, Snacks, Sweet treats",
    clubAgeSuitabilityUnder1S: false,
    clubAgeSuitability1To2Years: false,
    clubAgeSuitability3To4Years: false,
    clubAgeSuitability5To7Years: false,
    clubAgeSuitability8To12Years: true,
    clubAgeSuitabilityOver13Years: true,
    clubAgeSuitabilityAdults: false,
    clubActivityGroup: "Energy Burner, Low Effort, Moment of Peace",
    clubPhysicalSetting: "Inside",
    clubSkillArea: "Sport",
    clubSkillAreaVariant: "Climbing",
    clubAbilityLevel: "Intermediate",
    clubInterestTags: "Rock climbing, strength, agility, confidence",
    clubAttractions:
      "Confidence building, Strength & agility, Structured coaching, Purpose-built facilities, Climbing, All-weather options, Skill progression, Non-competitive options",
    clubExtraKit: "Activity-specific clothing",
    image: "Youth Climbing Club.JPG",
  },
  {
    opportunityType: "club",
    themeSlug: "sporty_activities",
    themeVariantSlug: "climbing_centre",
    clubName: "Monquays Climbing Club",
    clubDescription:
      "Monquays is a climbing club for primary school children in years 3-6 that will develop the core skills they need to become confident climbers and boulders. Based in the main climbing arena, children progress through a range of technical and physical challenges, all taught in a fun, engaging way that develops technique and physicial agility on the wall. ",
    clubFormat: "Training / Skill Development",
    clubCommittment: "Monthly",
    clubFrequency: "Weekly",
    clubAddressLine1: "The Quay Climbing Centre",
    clubAddressLine2: "Haven Road",
    clubCityTown: "Exeter",
    clubPostcode: "EX2 8AX",
    latitude: "50.7066",
    longitude: "-3.5007",
    clubStartDate: d("01/01/2026"),
    clubRepeatSession: true,
    clubDailySchedule:
      "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday",
    clubFixedDailyTimings: false,
    clubMixedTimingsMondayStartTime: "16:30",
    clubMixedTimingsMondayEndTime: "17:30",
    clubMixedTimingsTuesdayStartTime: "16:30",
    clubMixedTimingsTuesdayEndTime: "17:30",
    clubMixedTimingsWednesdayStartTime: "16:30",
    clubMixedTimingsWednesdayEndTime: "17:30",
    clubMixedTimingsThursdayStartTime: "16:30",
    clubMixedTimingsThursdayEndTime: "17:30",
    clubMixedTimingsFridayStartTime: "16:30",
    clubMixedTimingsFridayEndTime: "17:30",
    clubMultiSessionMondaySessionTotal: 4,
    clubMultiSessionMondaySchedule:
      "09:10-10:10, 10:20-11:20, 11:30-12:30, 18:00-19:00",
    clubMultiSessionTuesdaySessionTotal: 2,
    clubMultiSessionTuesdaySchedule: "10:00-11:00, 11:15-12:15",
    ticketingRequirement: true,
    clubBookingProvision: "Advance Book, Pre-Register",
    ticketingVariants: "(Fixed) Child",
    ticketVariantDefinitionFixedChild: "(Fixed) Child",
    ticketVariantDefinitionYoungChild: "7-11",
    ticketVariantYoungChildPrice: "£32.00",
    clubParkingProvision: "Paid Car Park, On-street / nearby parking",
    clubGeneralFacilities:
      "Toilets, Showers / changing facilities, Indoor Seating",
    clubAdultFacilities:
      "Hot Drinks, Comfy Seating / Sofas, Hot & Cold food, Snacks, Sweet treats",
    clubAgeSuitabilityUnder1S: false,
    clubAgeSuitability1To2Years: false,
    clubAgeSuitability3To4Years: false,
    clubAgeSuitability5To7Years: true,
    clubAgeSuitability8To12Years: true,
    clubAgeSuitabilityOver13Years: false,
    clubAgeSuitabilityAdults: false,
    clubActivityGroup: "Energy Burner, Low Effort, Moment of Peace",
    clubPhysicalSetting: "Inside",
    clubSkillArea: "Sport",
    clubSkillAreaVariant: "Climbing",
    clubAbilityLevel: "Beginner",
    clubInterestTags: "Rock climbing, strength, agility, confidence",
    clubAttractions:
      "Confidence building, Coordination & balance, Strength & agility, Structured coaching, Mixed-ability sessions, Purpose-built facilities, Climbing, All-weather options, Skill progression, Non-competitive options",
    clubExtraKit: "Activity-specific clothing",
    image: "Monquays Climbing Club.JPG",
  },
  {
    opportunityType: "club",
    themeSlug: "sporty_activities",
    themeVariantSlug: "climbing_centre",
    clubName: "Rockstars Climbing Club",
    clubDescription:
      "Rockstars is the Quay Climbing Centre's club for young climbing enthusiasts where confidence, coordination and balance is developed on the walls within the Clip 'n Climb arena. A starting point for children keen to develop the skills that will help them to move onto the bigger, roped climbing area with confidence. Run by experienced climbers who pass along their enthusiasm for the sport and teach through fun activities designed to develop technique and agility. ",
    clubFormat: "Training / Skill Development",
    clubCommittment: "Monthly",
    clubFrequency: "Weekly",
    clubAddressLine1: "The Quay Climbing Centre",
    clubAddressLine2: "Haven Road",
    clubCityTown: "Exeter",
    clubPostcode: "EX2 8AX",
    latitude: "50.7066",
    longitude: "-3.5007",
    clubStartDate: d("01/01/2026"),
    clubRepeatSession: false,
    clubDailySchedule: "Tuesday, Wednesday, Thursday",
    clubFixedDailyTimings: true,
    clubDailyStartTime: "16:30",
    clubDailyEndTime: "17:30",
    ticketingRequirement: true,
    clubBookingProvision: "Advance Book, Pre-Register",
    ticketingVariants: "Young Child",
    ticketVariantDefinitionYoungChild: "4-7",
    ticketVariantYoungChildPrice: "£32.00",
    clubParkingProvision: "Paid Car Park, On-street / nearby parking",
    clubGeneralFacilities:
      "Toilets, Showers / changing facilities, Indoor Seating",
    clubAdultFacilities:
      "Hot Drinks, Comfy Seating / Sofas, Hot & Cold food, Snacks, Sweet treats",
    clubAgeSuitabilityUnder1S: false,
    clubAgeSuitability1To2Years: false,
    clubAgeSuitability3To4Years: true,
    clubAgeSuitability5To7Years: true,
    clubAgeSuitability8To12Years: false,
    clubAgeSuitabilityOver13Years: false,
    clubAgeSuitabilityAdults: false,
    clubActivityGroup: "Energy Burner, Low Effort, Moment of Peace",
    clubPhysicalSetting: "Inside",
    clubSkillArea: "Sport",
    clubSkillAreaVariant: "Climbing",
    clubAbilityLevel: "None / Novice",
    clubInterestTags: "Rock climbing, balance, strength, agility, confidence",
    clubAttractions:
      "Early access introduction, Confidence building, Coordination & balance, Strength & agility, Structured coaching, Mixed-ability sessions, Purpose-built facilities, Climbing, All-weather options",
    clubExtraKit: "Activity-specific clothing",
    image: "Rockstars Climbing Club.JPG",
  },
  {
    opportunityType: "club",
    themeSlug: "sporty_activities",
    themeVariantSlug: "community_centre",
    clubName: "Little Yammas Martial Arts Exmouth",
    clubDescription:
      "The Lil YAMA’s programme offers children a great blend of fun & discipline whilst learning martial arts-based drills and games. Classes focus on building valuable life skills and developing a budding sense of discipline and concentration. High-energy, friendly and fun, instructors encourage enable children to take pride in developing their technique and discover the rewards of practice.",
    clubFormat: "Training / Skill Development",
    clubCommittment: "Monthly",
    clubFrequency: "Weekly",
    clubAddressLine1: "Withycombe Raleigh Primary School",
    clubAddressLine2: "187 Withycombe Village Road",
    clubCityTown: "Exmouth",
    clubPostcode: "EX8 3BA",
    latitude: "50.6294",
    longitude: "-3.4028",
    clubStartDate: d("01/01/2026"),
    clubRepeatSession: false,
    clubDailySchedule: "Monday, Tuesday, Thursday",
    clubFixedDailyTimings: true,
    clubDailyStartTime: "16:45",
    clubDailyEndTime: "17:25",
    ticketingRequirement: true,
    clubBookingProvision: "Advance Book, Pre-Register",
    ticketingVariants: "(Fixed) Child",
    ticketVariantDefinitionFixedChild: "(Fixed) Child",
    ticketVariantDefinitionYoungChild: "4-7",
    ticketVariantYoungChildPrice: "£29.00",
    clubParkingProvision: "Free Car Park",
    clubGeneralFacilities: "Toilets",
    clubAgeSuitabilityUnder1S: false,
    clubAgeSuitability1To2Years: false,
    clubAgeSuitability3To4Years: true,
    clubAgeSuitability5To7Years: true,
    clubAgeSuitability8To12Years: false,
    clubAgeSuitabilityOver13Years: false,
    clubAgeSuitabilityAdults: false,
    clubActivityGroup: "Energy Burner, Low Effort",
    clubPhysicalSetting: "Inside",
    clubSkillArea: "Sport",
    clubSkillAreaVariant: "Gymnastics & Martial Arts",
    clubAbilityLevel: "None / Novice",
    clubInterestTags:
      "Martial arts, confidence, skills development, ninja training",
    clubAttractions:
      "Early access introduction, Confidence building, Coordination & balance, Mixed-ability sessions, Friendly competition, Martial Arts",
    clubExtraKit: "Activity-specific clothing",
    image: "Little Yammas Martial Arts Exmouth.JPG",
  },
];
