import type {
  OpportunityVenueV2,
  OpportunityEventV2,
  OpportunityClubV2,
  OpportunityRouteV2,
} from '../../types/opportunity-v2.types';

const s = (v: unknown): string | null => (typeof v === 'string' && v !== '' ? v : null);
const b = (v: unknown): boolean | null => (typeof v === 'boolean' ? v : null);
const n = (v: unknown): number | null  => (typeof v === 'number'  ? v : null);
const d = (v: unknown): Date | null    => (v != null ? new Date(v as string) : null);

function themeRef(item: Record<string, unknown>, defaultType: string) {
  const slug    = (item['themeSlug']        as string) ?? '';
  const varSlug = (item['themeVariantSlug'] as string) ?? '';
  const oppType = (item['opportunityType']  as string) ?? defaultType;
  return {
    theme:        { id: slug,    slug,    name: slug,    recordType: oppType },
    themeVariant: { id: varSlug, slug: varSlug, name: varSlug },
    opportunityType: oppType,
  };
}

// ── Venue ─────────────────────────────────────────────────────────────────────

export function enrichVenue(item: Record<string, unknown>): OpportunityVenueV2 {
  const { theme, themeVariant, opportunityType } = themeRef(item, 'venue');
  return {
    id: item['id'] as string,
    opportunityType,
    theme,
    themeVariant,
    venueName:                        (item['venueName'] as string) ?? '',
    venueActivityGroup:               s(item['venueActivityGroup']),
    venueDescription:                 s(item['venueDescription']),
    venueAddressLine1:                s(item['venueAddressLine1']),
    venueAddressLine2:                s(item['venueAddressLine2']),
    venueCity:                        s(item['venueCity']),
    venueRegion:                      s(item['venueRegion']),
    venuePostcode:                    s(item['venuePostcode']),
    latitude:                         s(item['latitude']),
    longitude:                        s(item['longitude']),
    venueCountry:                     s(item['venueCountry']),
    venueSchedulePattern:             s(item['venueSchedulePattern']),
    venueFixedDailyTimings:           b(item['venueFixedDailyTimings']),
    venueFixedTimingsStartTime:       s(item['venueFixedTimingsStartTime']),
    venueFixedTimingsEndTime:         s(item['venueFixedTimingsEndTime']),
    venueMixedTimingsMondayStart:     s(item['venueMixedTimingsMondayStart']),
    venueMixedTimingsMondayEnd:       s(item['venueMixedTimingsMondayEnd']),
    venueMixedTimingsTuesdayStart:    s(item['venueMixedTimingsTuesdayStart']),
    venueMixedTimingsTuesdayEnd:      s(item['venueMixedTimingsTuesdayEnd']),
    venueMixedTimingsWednesdayStart:  s(item['venueMixedTimingsWednesdayStart']),
    venueMixedTimingsWednesdayEnd:    s(item['venueMixedTimingsWednesdayEnd']),
    venueMixedTimingsThursdayStart:   s(item['venueMixedTimingsThursdayStart']),
    venueMixedTimingsThursdayEnd:     s(item['venueMixedTimingsThursdayEnd']),
    venueMixedTimingsFridayStart:     s(item['venueMixedTimingsFridayStart']),
    venueMixedTimingsFridayEnd:       s(item['venueMixedTimingsFridayEnd']),
    venueMixedTimingsSaturdayStart:   s(item['venueMixedTimingsSaturdayStart']),
    venueMixedTimingsSaturdayEnd:     s(item['venueMixedTimingsSaturdayEnd']),
    venueMixedTimingsSundayStart:     s(item['venueMixedTimingsSundayStart']),
    venueMixedTimingsSundayEnd:       s(item['venueMixedTimingsSundayEnd']),
    venueEntryCost:                   b(item['venueEntryCost']),
    ticketingRequirement:             b(item['ticketingRequirement']),
    venueBookingType:                 s(item['venueBookingType']),
    ticketingVariants:                s(item['ticketingVariants']),
    ticketVariantDefinitionBaby:      s(item['ticketVariantDefinitionBaby']),
    ticketVariantBabyPrice:           s(item['ticketVariantBabyPrice']),
    ticketVariantDefinitionFixedChild:s(item['ticketVariantDefinitionFixedChild']),
    ticketVariantFixedChildPrice:     s(item['ticketVariantFixedChildPrice']),
    ticketVariantDefinitionYoungChild:s(item['ticketVariantDefinitionYoungChild']),
    ticketVariantYoungChildPrice:     s(item['ticketVariantYoungChildPrice']),
    ticketVariantDefinitionOlderChild:s(item['ticketVariantDefinitionOlderChild']),
    ticketVariantOlderChildPrice:     s(item['ticketVariantOlderChildPrice']),
    ticketVariantDefinitionAdult:     s(item['ticketVariantDefinitionAdult']),
    ticketVariantAdultPrice:          s(item['ticketVariantAdultPrice']),
    ticketVariantDefinitionConcession:s(item['ticketVariantDefinitionConcession']),
    ticketVariantConcessionPrice:     s(item['ticketVariantConcessionPrice']),
    ticketVariantDefinitionGroup:     s(item['ticketVariantDefinitionGroup']),
    ticketVariantGroupPrice:          s(item['ticketVariantGroupPrice']),
    venueGeneralFacilities:           s(item['venueGeneralFacilities']),
    venueChildFacilities:             s(item['venueChildFacilities']),
    venueAdultFacilities:             s(item['venueAdultFacilities']),
    venueDogFacilities:               s(item['venueDogFacilities']),
    venueParkingProvision:            s(item['venueParkingProvision']),
    venueAgeSuitabilityUnder1Years:   b(item['venueAgeSuitabilityUnder1Years']),
    venueAgeSuitability1To2Years:     b(item['venueAgeSuitability1To2Years']),
    venueAgeSuitability3To4Years:     b(item['venueAgeSuitability3To4Years']),
    venueAgeSuitability5To7Years:     b(item['venueAgeSuitability5To7Years']),
    venueAgeSuitability8To12Years:    b(item['venueAgeSuitability8To12Years']),
    venueAgeSuitabilityOver13Years:   b(item['venueAgeSuitabilityOver13Years']),
    venueAgeSuitabilityAdults:        b(item['venueAgeSuitabilityAdults']),
    venuePhysicalSetting:             s(item['venuePhysicalSetting']),
    venueDetailedWeatherSuitability:  s(item['venueDetailedWeatherSuitability']),
    venueEstimatedDuration:           s(item['venueEstimatedDuration']),
    venueInterestTags:                s(item['venueInterestTags']),
    venueSeasonalTag:                 s(item['venueSeasonalTag']),
    venueSeasonalHighlights:          s(item['venueSeasonalHighlights']),
    venueAttractions:                 s(item['venueAttractions']),
    venueExtraKit:                    s(item['venueExtraKit']),
    image:                            s(item['image']),
    createdAt:                        new Date(item['createdAt'] as string),
    updatedAt:                        new Date(item['updatedAt'] as string),
  };
}

// ── Event ─────────────────────────────────────────────────────────────────────

export function enrichEvent(item: Record<string, unknown>): OpportunityEventV2 {
  const { theme, themeVariant, opportunityType } = themeRef(item, 'event');
  return {
    id: item['id'] as string,
    opportunityType,
    theme,
    themeVariant,
    eventName:                        (item['eventName'] as string) ?? '',
    eventActivityGroup:               s(item['eventActivityGroup']),
    eventType:                        s(item['eventType']),
    eventDescription:                 s(item['eventDescription']),
    eventAddressLine1:                s(item['eventAddressLine1']),
    eventAddressLine2:                s(item['eventAddressLine2']),
    eventCity:                        s(item['eventCity']),
    eventRegion:                      s(item['eventRegion']),
    eventPostcode:                    s(item['eventPostcode']),
    eventCountry:                     s(item['eventCountry']),
    latitude:                         s(item['latitude']),
    longitude:                        s(item['longitude']),
    eventPhysicalSetting:             s(item['eventPhysicalSetting']),
    eventDetailedWeatherSuitability:  s(item['eventDetailedWeatherSuitability']),
    eventStartDate:                   d(item['eventStartDate']),
    eventEndDate:                     d(item['eventEndDate']),
    eventDaysTotal:                   n(item['eventDaysTotal']),
    eventDailyMultiSession:           b(item['eventDailyMultiSession']),
    eventTimetableWeekly:             s(item['eventTimetableWeekly']),
    eventDailyFixedTimings:           b(item['eventDailyFixedTimings']),
    eventDailyFixedStartTime:         s(item['eventDailyFixedStartTime']),
    eventDailyFixedEndTime:           s(item['eventDailyFixedEndTime']),
    eventDailyMultiSessionTotal:      n(item['eventDailyMultiSessionTotal']),
    eventDailyMultiSessionTimings:    s(item['eventDailyMultiSessionTimings']),
    eventWeeklyFixedStartTime:        s(item['eventWeeklyFixedStartTime']),
    eventWeeklyFixedEndTime:          s(item['eventWeeklyFixedEndTime']),
    eventMixedTimingsMondayStart:     s(item['eventMixedTimingsMondayStart']),
    eventMixedTimingsMondayEnd:       s(item['eventMixedTimingsMondayEnd']),
    eventMixedTimingsTuesdayStart:    s(item['eventMixedTimingsTuesdayStart']),
    eventMixedTimingsTuesdayEnd:      s(item['eventMixedTimingsTuesdayEnd']),
    eventMixedTimingsWednesdayStart:  s(item['eventMixedTimingsWednesdayStart']),
    eventMixedTimingsWednesdayEnd:    s(item['eventMixedTimingsWednesdayEnd']),
    eventMixedTimingsThursdayStart:   s(item['eventMixedTimingsThursdayStart']),
    eventMixedTimingsThursdayEnd:     s(item['eventMixedTimingsThursdayEnd']),
    eventMixedTimingsFridayStart:     s(item['eventMixedTimingsFridayStart']),
    eventMixedTimingsFridayEnd:       s(item['eventMixedTimingsFridayEnd']),
    eventMixedTimingsSaturdayStart:   s(item['eventMixedTimingsSaturdayStart']),
    eventMixedTimingsSaturdayEnd:     s(item['eventMixedTimingsSaturdayEnd']),
    eventMixedTimingsSundayStart:     s(item['eventMixedTimingsSundayStart']),
    eventMixedTimingsSundayEnd:       s(item['eventMixedTimingsSundayEnd']),
    ticketSalesStartDate:             d(item['ticketSalesStartDate']),
    eventEntryCost:                   b(item['eventEntryCost']),
    ticketingRequirement:             b(item['ticketingRequirement']),
    eventBookingType:                 s(item['eventBookingType']),
    ticketingVariants:                s(item['ticketingVariants']),
    ticketVariantDefinitionBaby:      s(item['ticketVariantDefinitionBaby']),
    ticketVariantBabyPrice:           s(item['ticketVariantBabyPrice']),
    ticketVariantDefinitionFixedChild:s(item['ticketVariantDefinitionFixedChild']),
    ticketVariantFixedChildPrice:     s(item['ticketVariantFixedChildPrice']),
    ticketVariantDefinitionYoungChild:s(item['ticketVariantDefinitionYoungChild']),
    ticketVariantYoungChildPrice:     s(item['ticketVariantYoungChildPrice']),
    ticketVariantDefinitionOlderChild:s(item['ticketVariantDefinitionOlderChild']),
    ticketVariantOlderChildPrice:     s(item['ticketVariantOlderChildPrice']),
    ticketVariantDefinitionAdult:     s(item['ticketVariantDefinitionAdult']),
    ticketVariantAdultPrice:          s(item['ticketVariantAdultPrice']),
    ticketVariantDefinitionConcession:s(item['ticketVariantDefinitionConcession']),
    ticketVariantConcessionPrice:     s(item['ticketVariantConcessionPrice']),
    ticketVariantDefinitionGroup:     s(item['ticketVariantDefinitionGroup']),
    ticketVariantGroupPrice:          s(item['ticketVariantGroupPrice']),
    eventParkingProvision:            s(item['eventParkingProvision']),
    eventGeneralFacilities:           s(item['eventGeneralFacilities']),
    eventChildFacilities:             s(item['eventChildFacilities']),
    eventAdultFacilities:             s(item['eventAdultFacilities']),
    eventAgeSuitabilityUnder1S:       b(item['eventAgeSuitabilityUnder1S']),
    eventAgeSuitability1To2Years:     b(item['eventAgeSuitability1To2Years']),
    eventAgeSuitability3To4Years:     b(item['eventAgeSuitability3To4Years']),
    eventAgeSuitability5To7Years:     b(item['eventAgeSuitability5To7Years']),
    eventAgeSuitability8To12Years:    b(item['eventAgeSuitability8To12Years']),
    eventAgeSuitabilityOver13Years:   b(item['eventAgeSuitabilityOver13Years']),
    eventAgeSuitabilityAdults:        b(item['eventAgeSuitabilityAdults']),
    eventInterestTags:                s(item['eventInterestTags']),
    eventSeasonalTags:                s(item['eventSeasonalTags']),
    eventSeasonalHighlights:          s(item['eventSeasonalHighlights']),
    eventHighlights:                  s(item['eventHighlights']),
    eventExtraKit:                    s(item['eventExtraKit']),
    eventSkillArea:                   s(item['eventSkillArea']),
    eventSkillAreaVariant:            s(item['eventSkillAreaVariant']),
    eventAbilityLevel:                s(item['eventAbilityLevel']),
    image:                            s(item['image']),
    createdAt:                        new Date(item['createdAt'] as string),
    updatedAt:                        new Date(item['updatedAt'] as string),
  };
}

// ── Club ──────────────────────────────────────────────────────────────────────

export function enrichClub(item: Record<string, unknown>): OpportunityClubV2 {
  const { theme, themeVariant, opportunityType } = themeRef(item, 'club');
  return {
    id: item['id'] as string,
    opportunityType,
    theme,
    themeVariant,
    clubName:                             (item['clubName'] as string) ?? '',
    clubDescription:                      s(item['clubDescription']),
    clubFormat:                           s(item['clubFormat']),
    clubCommittment:                      s(item['clubCommittment']),
    clubFrequency:                        s(item['clubFrequency']),
    clubAddressLine1:                     s(item['clubAddressLine1']),
    clubAddressLine2:                     s(item['clubAddressLine2']),
    clubCityTown:                         s(item['clubCityTown']),
    clubStateRegionProvince:              s(item['clubStateRegionProvince']),
    clubPostcode:                         s(item['clubPostcode']),
    clubCountry:                          s(item['clubCountry']),
    latitude:                             s(item['latitude']),
    longitude:                            s(item['longitude']),
    clubStartDate:                        d(item['clubStartDate']),
    clubEndDate:                          d(item['clubEndDate']),
    clubRepeatSession:                    b(item['clubRepeatSession']),
    clubDailyFixedSessionTotal:           n(item['clubDailyFixedSessionTotal']),
    clubDailyFixedSessionSchedule:        s(item['clubDailyFixedSessionSchedule']),
    clubDailySchedule:                    s(item['clubDailySchedule']),
    clubFixedDailyTimings:                b(item['clubFixedDailyTimings']),
    clubDailyStartTime:                   s(item['clubDailyStartTime']),
    clubDailyEndTime:                     s(item['clubDailyEndTime']),
    clubMixedTimingsMondayStartTime:      s(item['clubMixedTimingsMondayStartTime']),
    clubMixedTimingsMondayEndTime:        s(item['clubMixedTimingsMondayEndTime']),
    clubMixedTimingsTuesdayStartTime:     s(item['clubMixedTimingsTuesdayStartTime']),
    clubMixedTimingsTuesdayEndTime:       s(item['clubMixedTimingsTuesdayEndTime']),
    clubMixedTimingsWednesdayStartTime:   s(item['clubMixedTimingsWednesdayStartTime']),
    clubMixedTimingsWednesdayEndTime:     s(item['clubMixedTimingsWednesdayEndTime']),
    clubMixedTimingsThursdayStartTime:    s(item['clubMixedTimingsThursdayStartTime']),
    clubMixedTimingsThursdayEndTime:      s(item['clubMixedTimingsThursdayEndTime']),
    clubMixedTimingsFridayStartTime:      s(item['clubMixedTimingsFridayStartTime']),
    clubMixedTimingsFridayEndTime:        s(item['clubMixedTimingsFridayEndTime']),
    clubMixedTimingsSaturdayStartTime:    s(item['clubMixedTimingsSaturdayStartTime']),
    clubMixedTimingsSaturdayEndTime:      s(item['clubMixedTimingsSaturdayEndTime']),
    clubMixedTimingsSundayStartTime:      s(item['clubMixedTimingsSundayStartTime']),
    clubMixedTimingsSundayEndTime:        s(item['clubMixedTimingsSundayEndTime']),
    clubMultiSessionMondaySessionTotal:   n(item['clubMultiSessionMondaySessionTotal']),
    clubMultiSessionMondaySchedule:       s(item['clubMultiSessionMondaySchedule']),
    clubMultiSessionTuesdaySessionTotal:  n(item['clubMultiSessionTuesdaySessionTotal']),
    clubMultiSessionTuesdaySchedule:      s(item['clubMultiSessionTuesdaySchedule']),
    clubMultiSessionWednesdaySessionTotal:n(item['clubMultiSessionWednesdaySessionTotal']),
    clubMultiSessionWednesdaySchedule:    s(item['clubMultiSessionWednesdaySchedule']),
    clubMultiSessionThursdaySessionTotal: n(item['clubMultiSessionThursdaySessionTotal']),
    clubMultiSessionThursdaySchedule:     s(item['clubMultiSessionThursdaySchedule']),
    clubMultiSessionFridaySessionTotal:   n(item['clubMultiSessionFridaySessionTotal']),
    clubMultiSessionFridaySchedule:       s(item['clubMultiSessionFridaySchedule']),
    clubMultiSessionSaturdaySessionTotal: n(item['clubMultiSessionSaturdaySessionTotal']),
    clubMultiSessionSaturdaySchedule:     s(item['clubMultiSessionSaturdaySchedule']),
    clubMultiSessionSundaySessionTotal:   n(item['clubMultiSessionSundaySessionTotal']),
    clubMultiSessionSundaySchedule:       s(item['clubMultiSessionSundaySchedule']),
    clubMonthlySchedule:                  s(item['clubMonthlySchedule']),
    clubFixedMonthOccurance:              s(item['clubFixedMonthOccurance']),
    clubMonthlyOccurance:                 s(item['clubMonthlyOccurance']),
    clubMonthlyFixedDates:                s(item['clubMonthlyFixedDates']),
    ticketingRequirement:                 b(item['ticketingRequirement']),
    clubBookingProvision:                 s(item['clubBookingProvision']),
    ticketingVariants:                    s(item['ticketingVariants']),
    ticketVariantDefinitionBaby:          s(item['ticketVariantDefinitionBaby']),
    ticketVariantBabyPrice:               s(item['ticketVariantBabyPrice']),
    ticketVariantDefinitionFixedChild:    s(item['ticketVariantDefinitionFixedChild']),
    ticketVariantFixedChildPrice:         s(item['ticketVariantFixedChildPrice']),
    ticketVariantDefinitionYoungChild:    s(item['ticketVariantDefinitionYoungChild']),
    ticketVariantYoungChildPrice:         s(item['ticketVariantYoungChildPrice']),
    ticketVariantDefinitionOlderChild:    s(item['ticketVariantDefinitionOlderChild']),
    ticketVariantOlderChildPrice:         s(item['ticketVariantOlderChildPrice']),
    ticketVariantDefinitionAdult:         s(item['ticketVariantDefinitionAdult']),
    ticketVariantAdultPrice:              s(item['ticketVariantAdultPrice']),
    ticketVariantDefinitionConcession:    s(item['ticketVariantDefinitionConcession']),
    ticketVariantConcessionPrice:         s(item['ticketVariantConcessionPrice']),
    ticketVariantDefinitionGroup:         s(item['ticketVariantDefinitionGroup']),
    ticketVariantGroupPrice:              s(item['ticketVariantGroupPrice']),
    clubParkingProvision:                 s(item['clubParkingProvision']),
    clubGeneralFacilities:                s(item['clubGeneralFacilities']),
    clubChildFacilities:                  s(item['clubChildFacilities']),
    clubAdultFacilities:                  s(item['clubAdultFacilities']),
    clubAgeSuitabilityUnder1S:            b(item['clubAgeSuitabilityUnder1S']),
    clubAgeSuitability1To2Years:          b(item['clubAgeSuitability1To2Years']),
    clubAgeSuitability3To4Years:          b(item['clubAgeSuitability3To4Years']),
    clubAgeSuitability5To7Years:          b(item['clubAgeSuitability5To7Years']),
    clubAgeSuitability8To12Years:         b(item['clubAgeSuitability8To12Years']),
    clubAgeSuitabilityOver13Years:        b(item['clubAgeSuitabilityOver13Years']),
    clubAgeSuitabilityAdults:             b(item['clubAgeSuitabilityAdults']),
    clubActivityGroup:                    s(item['clubActivityGroup']),
    clubPhysicalSetting:                  s(item['clubPhysicalSetting']),
    clubSkillArea:                        s(item['clubSkillArea']),
    clubSkillAreaVariant:                 s(item['clubSkillAreaVariant']),
    clubAbilityLevel:                     s(item['clubAbilityLevel']),
    clubInterestTags:                     s(item['clubInterestTags']),
    clubSeasonalTag:                      s(item['clubSeasonalTag']),
    clubSeasonalHighlights:               s(item['clubSeasonalHighlights']),
    clubAttractions:                      s(item['clubAttractions']),
    clubExtraKit:                         s(item['clubExtraKit']),
    image:                                s(item['image']),
    createdAt:                            new Date(item['createdAt'] as string),
    updatedAt:                            new Date(item['updatedAt'] as string),
  };
}

// ── Route ─────────────────────────────────────────────────────────────────────

export function enrichRoute(item: Record<string, unknown>): OpportunityRouteV2 {
  const { theme, themeVariant, opportunityType } = themeRef(item, 'route');
  return {
    id: item['id'] as string,
    opportunityType,
    theme,
    themeVariant,
    routeName:                       (item['routeName'] as string) ?? '',
    routeActivityGrouping:           s(item['routeActivityGrouping']),
    routeDescription:                s(item['routeDescription']),
    routeType:                       s(item['routeType']),
    routeDistance:                   s(item['routeDistance']),
    routeTerrainType:                s(item['routeTerrainType']),
    routeDifficulty:                 s(item['routeDifficulty']),
    routeAddressLine1:               s(item['routeAddressLine1']),
    routeAddressLine2:               s(item['routeAddressLine2']),
    routeRegion:                     s(item['routeRegion']),
    routePostcode:                   s(item['routePostcode']),
    latitude:                        s(item['latitude']),
    longitude:                       s(item['longitude']),
    routeCountry:                    s(item['routeCountry']),
    routeParkingProvision:           s(item['routeParkingProvision']),
    routeGeneralFacilities:          s(item['routeGeneralFacilities']),
    routeChildFacilities:            s(item['routeChildFacilities']),
    routeAdultFacilities:            s(item['routeAdultFacilities']),
    routeDogFacilities:              s(item['routeDogFacilities']),
    routeAgeSuitabilityUnder1S:      b(item['routeAgeSuitabilityUnder1S']),
    routeAgeSuitability1To2Years:    b(item['routeAgeSuitability1To2Years']),
    routeAgeSuitability3To4Years:    b(item['routeAgeSuitability3To4Years']),
    routeAgeSuitability5To7Years:    b(item['routeAgeSuitability5To7Years']),
    routeAgeSuitability8To12Years:   b(item['routeAgeSuitability8To12Years']),
    routeAgeSuitabilityOver13Years:  b(item['routeAgeSuitabilityOver13Years']),
    routeAgeSuitabilityAdults:       b(item['routeAgeSuitabilityAdults']),
    routePhysicalSetting:            s(item['routePhysicalSetting']),
    routeDetailedWeatherSuitability: s(item['routeDetailedWeatherSuitability']),
    routeEstimatedDuration:          s(item['routeEstimatedDuration']),
    routeInterestTags:               s(item['routeInterestTags']),
    routeSeasonalTag:                s(item['routeSeasonalTag']),
    routeSeasonalHighlights:         s(item['routeSeasonalHighlights']),
    routeAttractions:                s(item['routeAttractions']),
    routeExtraKit:                   s(item['routeExtraKit']),
    image:                           s(item['image']),
    createdAt:                       new Date(item['createdAt'] as string),
    updatedAt:                       new Date(item['updatedAt'] as string),
  };
}
