import * as fs from "node:fs";

export interface TypeField {
  name: string;
  tsType: string;
}

/**
 * Writes a plain TS interface reflecting exactly the fields a parser script
 * actually produces — not derived from any hand-maintained type elsewhere.
 * Each parse-*-data.ts script calls this with its own COLUMNS-derived field
 * list, so if a column is added/removed from that script, the type file is
 * regenerated to match on the next run instead of drifting out of sync.
 */
export function emitTypeFile(outputPath: string, typeName: string, sourceScript: string, fields: TypeField[]): void {
  const lines: string[] = [];
  lines.push(`// AUTO-GENERATED by ${sourceScript} — do not hand-edit.`);
  lines.push(`// Re-run that script (it reads the actual sheet columns) to regenerate this file.`);
  lines.push(`export interface ${typeName} {`);
  for (const f of fields) lines.push(`  ${f.name}: ${f.tsType};`);
  lines.push(`}`);
  lines.push(``);
  fs.writeFileSync(outputPath, lines.join("\n"));
}
