-- Event spreadsheet import (distinct from opportunity_venues_v2 venue import).

CREATE TABLE "opportunity_venue_v2" (
    "id" TEXT NOT NULL,
    "opportunity_type" "OpportunityRecordType" NOT NULL DEFAULT 'event',
    "event_opportunity_theme_id" TEXT NOT NULL,
    "event_opportunity_theme_variant_id" TEXT NOT NULL,
    "event_name" TEXT NOT NULL,
    "event_activity_group" TEXT,
    "event_type" TEXT,
    "event_description" TEXT,
    "event_address_line_1" TEXT,
    "event_address_line_2" TEXT,
    "event_city" TEXT,
    "event_region" TEXT,
    "event_postcode" VARCHAR(20),
    "event_country" TEXT,
    "latitude" TEXT,
    "longitude" TEXT,
    "event_physical_setting" TEXT,
    "event_detailed_weather_suitability" TEXT,
    "event_start_date" TIMESTAMP(3),
    "event_end_date" TIMESTAMP(3),
    "event_days_total" INTEGER,
    "event_daily_multi_session" BOOLEAN,
    "event_timetable_weekly" TEXT,
    "event_daily_fixed_timings" BOOLEAN,
    "event_daily_fixed_start_time" VARCHAR(5),
    "event_daily_fixed_end_time" VARCHAR(5),
    "event_daily_multi_session_total" INTEGER,
    "event_daily_multi_session_timings" TEXT,
    "event_weekly_fixed_start_time" VARCHAR(5),
    "event_weekly_fixed_end_time" VARCHAR(5),
    "event_mixed_timings_monday_start_time" VARCHAR(5),
    "event_mixed_timings_monday_end_time" VARCHAR(5),
    "event_mixed_timings_tuesday_start_time" VARCHAR(5),
    "event_mixed_timings_tuesday_end_time" VARCHAR(5),
    "event_mixed_timings_wednesday_start_time" VARCHAR(5),
    "event_mixed_timings_wednesday_end_time" VARCHAR(5),
    "event_mixed_timings_thursday_start_time" VARCHAR(5),
    "event_mixed_timings_thursday_end_time" VARCHAR(5),
    "event_mixed_timings_friday_start_time" VARCHAR(5),
    "event_mixed_timings_friday_end_time" VARCHAR(5),
    "event_mixed_timings_saturday_start_time" VARCHAR(5),
    "event_mixed_timings_saturday_end_time" VARCHAR(5),
    "event_mixed_timings_sunday_start_time" VARCHAR(5),
    "event_mixed_timings_sunday_end_time" VARCHAR(5),
    "ticket_sales_start_date" TIMESTAMP(3),
    "event_entry_cost" BOOLEAN,
    "event_booking_type" TEXT,
    "ticketing_variants" TEXT,
    "ticket_variant_definition_baby" TEXT,
    "ticket_variant_baby_price" TEXT,
    "ticket_variant_definition__fixed_child" TEXT,
    "ticket_variant_fixed_child_price" TEXT,
    "ticket_variant_definition_young_child" TEXT,
    "ticket_variant_young_child_price" TEXT,
    "ticket_variant_definition_older_child" TEXT,
    "ticket_variant_older_child_price" TEXT,
    "ticket_variant_definition_adult" TEXT,
    "ticket_variant_adult_price" TEXT,
    "ticket_variant_definition_concession" TEXT,
    "ticket_variant_concession_price" TEXT,
    "ticket_variant_definition_group" TEXT,
    "ticket_variant_group_price" TEXT,
    "event_parking_provision" TEXT,
    "event_general_facilities" TEXT,
    "event_child_facilities" TEXT,
    "event_adult_facilities" TEXT,
    "event_age_suitability_under_1_s" BOOLEAN,
    "event_age_suitability_1_to_2_years" BOOLEAN,
    "event_age_suitability_3_to_4_years" BOOLEAN,
    "event_age_suitability_5_to_7_years" BOOLEAN,
    "event_age_suitability_8_to_12_years" BOOLEAN,
    "event_age_suitability_over_13_years" BOOLEAN,
    "event_age_suitability_adults" BOOLEAN,
    "event_interest_tags" TEXT,
    "event_seasonal_tags" TEXT,
    "event_seasonal_highlights" TEXT,
    "event_highlights" TEXT,
    "event_extra_kit" TEXT,
    "event_skill_area" TEXT,
    "event_skill_area_variant" TEXT,
    "event_ability_level" TEXT,
    "image" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "opportunity_venue_v2_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "opportunity_venue_v2_event_opportunity_theme_id_idx" ON "opportunity_venue_v2"("event_opportunity_theme_id");

CREATE INDEX "opportunity_venue_v2_event_opportunity_theme_variant_id_idx" ON "opportunity_venue_v2"("event_opportunity_theme_variant_id");

ALTER TABLE "opportunity_venue_v2" ADD CONSTRAINT "opportunity_venue_v2_event_opportunity_theme_id_fkey" FOREIGN KEY ("event_opportunity_theme_id") REFERENCES "opportunity_theme"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "opportunity_venue_v2" ADD CONSTRAINT "opportunity_venue_v2_event_opportunity_theme_variant_id_fkey" FOREIGN KEY ("event_opportunity_theme_variant_id") REFERENCES "opportunity_theme_variant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
