export interface OpportunityClubV2ThemeRef {
  id: string;
  slug: string;
  name: string;
  recordType: string;
}

export interface OpportunityClubV2ThemeVariantRef {
  id: string;
  slug: string;
  name: string;
}

/** API shape: spreadsheet-style scalars plus theme rows stored inline. */
export interface OpportunityClubV2Response {
  id: string;
  opportunityType: string;
  theme: OpportunityClubV2ThemeRef;
  themeVariant: OpportunityClubV2ThemeVariantRef;
  clubName: string;
  clubDescription: string | null;
  clubFormat: string | null;
  clubCommittment: string | null;
  clubFrequency: string | null;
  clubAddressLine1: string | null;
  clubAddressLine2: string | null;
  clubCityTown: string | null;
  clubStateRegionProvince: string | null;
  clubPostcode: string | null;
  clubCountry: string | null;
  latitude: string | null;
  longitude: string | null;
  clubStartDate: Date | null;
  clubEndDate: Date | null;
  clubRepeatSession: boolean | null;
  clubDailyFixedSessionTotal: number | null;
  clubDailyFixedSessionSchedule: string | null;
  clubDailySchedule: string | null;
  clubFixedDailyTimings: boolean | null;
  clubDailyStartTime: string | null;
  clubDailyEndTime: string | null;
  clubMixedTimingsMondayStartTime: string | null;
  clubMixedTimingsMondayEndTime: string | null;
  clubMixedTimingsTuesdayStartTime: string | null;
  clubMixedTimingsTuesdayEndTime: string | null;
  clubMixedTimingsWednesdayStartTime: string | null;
  clubMixedTimingsWednesdayEndTime: string | null;
  clubMixedTimingsThursdayStartTime: string | null;
  clubMixedTimingsThursdayEndTime: string | null;
  clubMixedTimingsFridayStartTime: string | null;
  clubMixedTimingsFridayEndTime: string | null;
  clubMixedTimingsSaturdayStartTime: string | null;
  clubMixedTimingsSaturdayEndTime: string | null;
  clubMixedTimingsSundayStartTime: string | null;
  clubMixedTimingsSundayEndTime: string | null;
  clubMultiSessionMondaySessionTotal: number | null;
  clubMultiSessionMondaySchedule: string | null;
  clubMultiSessionTuesdaySessionTotal: number | null;
  clubMultiSessionTuesdaySchedule: string | null;
  clubMultiSessionWednesdaySessionTotal: number | null;
  clubMultiSessionWednesdaySchedule: string | null;
  clubMultiSessionThursdaySessionTotal: number | null;
  clubMultiSessionThursdaySchedule: string | null;
  clubMultiSessionFridaySessionTotal: number | null;
  clubMultiSessionFridaySchedule: string | null;
  clubMultiSessionSaturdaySessionTotal: number | null;
  clubMultiSessionSaturdaySchedule: string | null;
  clubMultiSessionSundaySessionTotal: number | null;
  clubMultiSessionSundaySchedule: string | null;
  clubMonthlySchedule: string | null;
  clubFixedMonthOccurance: string | null;
  clubMonthlyOccurance: string | null;
  clubMonthlyFixedDates: string | null;
  ticketingRequirement: boolean | null;
  clubBookingProvision: string | null;
  ticketingVariants: string | null;
  ticketVariantDefinitionBaby: string | null;
  ticketVariantBabyPrice: string | null;
  ticketVariantDefinitionFixedChild: string | null;
  ticketVariantFixedChildPrice: string | null;
  ticketVariantDefinitionYoungChild: string | null;
  ticketVariantYoungChildPrice: string | null;
  ticketVariantDefinitionOlderChild: string | null;
  ticketVariantOlderChildPrice: string | null;
  ticketVariantDefinitionAdult: string | null;
  ticketVariantAdultPrice: string | null;
  ticketVariantDefinitionConcession: string | null;
  ticketVariantConcessionPrice: string | null;
  ticketVariantDefinitionGroup: string | null;
  ticketVariantGroupPrice: string | null;
  clubParkingProvision: string | null;
  clubGeneralFacilities: string | null;
  clubChildFacilities: string | null;
  clubAdultFacilities: string | null;
  clubAgeSuitabilityUnder1S: boolean | null;
  clubAgeSuitability1To2Years: boolean | null;
  clubAgeSuitability3To4Years: boolean | null;
  clubAgeSuitability5To7Years: boolean | null;
  clubAgeSuitability8To12Years: boolean | null;
  clubAgeSuitabilityOver13Years: boolean | null;
  clubAgeSuitabilityAdults: boolean | null;
  clubActivityGroup: string | null;
  clubPhysicalSetting: string | null;
  clubSkillArea: string | null;
  clubSkillAreaVariant: string | null;
  clubAbilityLevel: string | null;
  clubInterestTags: string | null;
  clubSeasonalTag: string | null;
  clubSeasonalHighlights: string | null;
  clubAttractions: string | null;
  clubExtraKit: string | null;
  image: string | null;
  createdAt: Date;
  updatedAt: Date;
}
