import type { OpportunityVenueV2SeedInput } from "../create_opportunity_venue_v2.js";

export const candysFieldPlayParkVenueV2: OpportunityVenueV2SeedInput = {
  opportunityType: "venue",
  themeSlug: "playgrounds_and_adventure_play",
  themeVariantSlug: "local_playgrounds",
  venueName: "Candy's Field Play Park",
  venueActivityGroup: "Simple Reset, Energy Burner, Low Effort",
  venueDescription:
    "Beloved village park sat within Candy's Field, the playing fields in the heart of Lympstone Village, adjacent to the local school and village hall. Basketball courts, old fallen trees and a wooden obstacle-style course offers a variety of play options best suited to Primary aged children. Busy on fair weather days after school hours, but quiet at weekends, it's a short walk from the local train station, Exe Estuary trail and local village shop and cafe.",
  venueAddressLine1: "Candy's Field",
  venueAddressLine2: "School Hill",
  venueCity: "Lympstone",
  venueRegion: "Devon",
  venuePostcode: "EX8 5JY",
  latitude: "50.650095",
  longitude: "-3.426747",
  venueCountry: null,
  venueSchedulePattern:
    "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday",
  venueFixedDailyTimings: true,
  venueFixedTimingsStartTime: "12:00",
  venueFixedTimingsEndTime: "12:00",
  venueEntryCost: false,
  ticketingRequirement: false,
  venueBookingType: "Open (Free) Access",
  ticketingVariants: null,
  ticketVariantDefinitionBaby: "-",
  ticketVariantBabyPrice: "£0.00",
  ticketVariantDefinitionFixedChild: "-",
  ticketVariantFixedChildPrice: "£0.00",
  ticketVariantDefinitionYoungChild: "-",
  ticketVariantYoungChildPrice: "£0.00",
  ticketVariantDefinitionOlderChild: "-",
  ticketVariantOlderChildPrice: "£0.00",
  ticketVariantDefinitionAdult: "-",
  ticketVariantAdultPrice: "£0.00",
  ticketVariantDefinitionConcession: "-",
  ticketVariantConcessionPrice: "£0.00",
  ticketVariantDefinitionGroup: "-",
  ticketVariantGroupPrice: "£0.00",
  venueParkingProvision: "On-street / nearby parking",
  venueGeneralFacilities: "Bench Seating, Picnic Benches",
  venueChildFacilities: "Outdoor play equipment",
  venueAdultFacilities: "Clear Sightlines",
  venueDogFacilities: null,
  venueAgeSuitabilityUnder1Years: false,
  venueAgeSuitability1To2Years: true,
  venueAgeSuitability3To4Years: true,
  venueAgeSuitability5To7Years: true,
  venueAgeSuitability8To12Years: false,
  venueAgeSuitabilityOver13Years: false,
  venueAgeSuitabilityAdults: false,
  venuePhysicalSetting: "Outside",
  venueDetailedWeatherSuitability:
    "Sunshine, Overcast / cloudy, Dry & mild, Dry & cold, Dry & warm, Dry & hot",
  venueEstimatedDuration: "Under 30mins",
  venueInterestTags: "obstacle course, football, basketball",
  venueSeasonalTag: null,
  venueSeasonalHighlights: null,
  venueAttractions:
    "Balance elements, Stepping obstacles, Zip wires, Clear sightlines for adults",
  venueExtraKit: null,
  image: "Candy's Field Play Park.JPG",
};
