import type { OpportunityVenueV2SeedInput } from "../create_opportunity_venue_v2.js";

export const exmouthQueensParadePlayAreaVenueV2: OpportunityVenueV2SeedInput = {
  opportunityType: "venue",
  themeSlug: "playgrounds_and_adventure_play",
  themeVariantSlug: "local_playgrounds",
  venueName: "Exmouth Queens Parade Play Area (Dino Park)",
  venueActivityGroup: "Simple Reset, Energy Burner, Low Effort",
  venueDescription:
    "Seafront park that offers a great pitstop after a trip to the beach or nearby leisure facilities. Jurrasic-themed, the large sandpit hides fossils to be uncovered, and a giant dinosaur slide takes centre-stage, surrounded by wooden play equipment, swings and picnic benches. ",
  venueAddressLine1: "Queen's Drive Space",
  venueAddressLine2: "Exmouth Seafront",
  venueCity: "Exmouth",
  venueRegion: "Devon",
  venuePostcode: "EX8 2AY",
  latitude: "50.613627",
  longitude: "-3.407437",
  venueCountry: null,
  venueSchedulePattern:
    "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday",
  venueFixedDailyTimings: true,
  venueFixedTimingsStartTime: "12:00",
  venueFixedTimingsEndTime: "12:00",
  venueEntryCost: false,
  ticketingRequirement: false,
  venueBookingType: "Open (Free) Access",
  ticketingVariants: null,
  ticketVariantDefinitionBaby: "-",
  ticketVariantBabyPrice: "£0.00",
  ticketVariantDefinitionFixedChild: "-",
  ticketVariantFixedChildPrice: "£0.00",
  ticketVariantDefinitionYoungChild: "-",
  ticketVariantYoungChildPrice: "£0.00",
  ticketVariantDefinitionOlderChild: "-",
  ticketVariantOlderChildPrice: "£0.00",
  ticketVariantDefinitionAdult: "-",
  ticketVariantAdultPrice: "£0.00",
  ticketVariantDefinitionConcession: "-",
  ticketVariantConcessionPrice: "£0.00",
  ticketVariantDefinitionGroup: "-",
  ticketVariantGroupPrice: "£0.00",
  venueParkingProvision: "Paid Car Park",
  venueGeneralFacilities: "Bench Seating, Picnic Benches",
  venueChildFacilities:
    "Ice creams, Sandpit, Swings, Slides, Climbing Frames, Outdoor play equipment",
  venueAdultFacilities: null,
  venueDogFacilities: null,
  venueAgeSuitabilityUnder1Years: false,
  venueAgeSuitability1To2Years: true,
  venueAgeSuitability3To4Years: true,
  venueAgeSuitability5To7Years: true,
  venueAgeSuitability8To12Years: false,
  venueAgeSuitabilityOver13Years: false,
  venueAgeSuitabilityAdults: false,
  venuePhysicalSetting: "Outside",
  venueDetailedWeatherSuitability:
    "Sunshine, Overcast / cloudy, Dry & mild, Dry & cold, Dry & warm, Dry & hot",
  venueEstimatedDuration: "30-60mins",
  venueInterestTags:
    "helter-skelter slide, wooden structures, swings, sandpit",
  venueSeasonalTag: null,
  venueSeasonalHighlights: null,
  venueAttractions:
    "Rope bridges, Slides (particularly tall or long)",
  venueExtraKit: "Sand toys, Beach toys",
  image: "Queen's Parade Play Park.JPG",
};
