-- PostgreSQL appends new columns to the end of the table; rebuild so `venue_dog_facilities`
-- sits with general / child / adult / parking (matches Prisma model order).

ALTER TABLE "opportunity_venue_v2" DROP CONSTRAINT "opportunity_venue_v2_venue_opportunity_theme_id_fkey";
ALTER TABLE "opportunity_venue_v2" DROP CONSTRAINT "opportunity_venue_v2_venue_opportunity_theme_variant_id_fkey";

DROP INDEX IF EXISTS "opportunity_venue_v2_venue_opportunity_theme_id_idx";
DROP INDEX IF EXISTS "opportunity_venue_v2_venue_opportunity_theme_variant_id_idx";

ALTER TABLE "opportunity_venue_v2" RENAME TO "opportunity_venue_v2_old";

ALTER TABLE "opportunity_venue_v2_old" RENAME CONSTRAINT "opportunity_venue_v2_pkey" TO "opportunity_venue_v2_old_pkey";

CREATE TABLE "opportunity_venue_v2" (
    "id" TEXT NOT NULL,
    "opportunity_type" "OpportunityRecordType" NOT NULL DEFAULT 'venue',
    "venue_opportunity_theme_id" TEXT NOT NULL,
    "venue_opportunity_theme_variant_id" TEXT NOT NULL,
    "venue_name" TEXT NOT NULL,
    "venue_activity_group" TEXT,
    "venue_description" TEXT,
    "venue_address_line_1" TEXT,
    "venue_address_line_2" TEXT,
    "venue_city" TEXT,
    "venue_region" TEXT,
    "venue_postcode" VARCHAR(20),
    "latitude" TEXT,
    "longitude" TEXT,
    "venue_country" TEXT,
    "venue_schedule_pattern" TEXT,
    "venue_fixed_daily_timings" BOOLEAN,
    "venue_fixed_timings_start_time" VARCHAR(5),
    "venue_fixed_timings_end_time" VARCHAR(5),
    "venue_mixed_timings_monday_start_time" VARCHAR(5),
    "venue_mixed_timings_monday_end_time" VARCHAR(5),
    "venue_mixed_timings_tuesday_start_time" VARCHAR(5),
    "venue_mixed_timings_tuesday_end_time" VARCHAR(5),
    "venue_mixed_timings_wednesday_start_time" VARCHAR(5),
    "venue_mixed_timings_wednesday_end_time" VARCHAR(5),
    "venue_mixed_timings_thursday_start_time" VARCHAR(5),
    "venue_mixed_timings_thursday_end_time" VARCHAR(5),
    "venue_mixed_timings_friday_start_time" VARCHAR(5),
    "venue_mixed_timings_friday_end_time" VARCHAR(5),
    "venue_mixed_timings_saturday_start_time" VARCHAR(5),
    "venue_mixed_timings_saturday_end_time" VARCHAR(5),
    "venue_mixed_timings_sunday_start_time" VARCHAR(5),
    "venue_mixed_timings_sunday_end_time" VARCHAR(5),
    "venue_entry_cost" BOOLEAN,
    "ticketing_requirement" BOOLEAN,
    "venue_booking_type" TEXT,
    "ticketing_variants" TEXT,
    "ticket_variant_definition_baby" TEXT,
    "ticket_variant_baby_price" TEXT,
    "ticket_variant_definition__fixed_child" TEXT,
    "ticket_variant_fixed_child_price" TEXT,
    "ticket_variant_definition_young_child" TEXT,
    "ticket_variant_young_child_price" TEXT,
    "ticket_variant_definition_older_child" TEXT,
    "ticket_variant_older_child_price" TEXT,
    "ticket_variant_definition_adult" TEXT,
    "ticket_variant_adult_price" TEXT,
    "ticket_variant_definition_concession" TEXT,
    "ticket_variant_concession_price" TEXT,
    "ticket_variant_definition_group" TEXT,
    "ticket_variant_group_price" TEXT,
    "venue_general_facilities" TEXT,
    "venue_child_facilities" TEXT,
    "venue_adult_facilities" TEXT,
    "venue_dog_facilities" TEXT,
    "venue_parking_provision" TEXT,
    "venue_age_suitability_under_1_s" BOOLEAN,
    "venue_age_suitability_1_to_2_years" BOOLEAN,
    "venue_age_suitability_3_to_4_years" BOOLEAN,
    "venue_age_suitability_5_to_7_years" BOOLEAN,
    "venue_age_suitability_8_to_12_years" BOOLEAN,
    "venue_age_suitability_over_13_years" BOOLEAN,
    "venue_age_suitability_adults" BOOLEAN,
    "venue_physical_setting" TEXT,
    "venue_detailed_weather_suitability" TEXT,
    "venue_estimated_duration" TEXT,
    "venue_interest_tags" TEXT,
    "venue_seasonal_tag" TEXT,
    "venue_seasonal_highlights" TEXT,
    "venue_attractions" TEXT,
    "venue_extra_kit" TEXT,
    "image" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "opportunity_venue_v2_pkey" PRIMARY KEY ("id")
);

INSERT INTO "opportunity_venue_v2" (
    "id",
    "opportunity_type",
    "venue_opportunity_theme_id",
    "venue_opportunity_theme_variant_id",
    "venue_name",
    "venue_activity_group",
    "venue_description",
    "venue_address_line_1",
    "venue_address_line_2",
    "venue_city",
    "venue_region",
    "venue_postcode",
    "latitude",
    "longitude",
    "venue_country",
    "venue_schedule_pattern",
    "venue_fixed_daily_timings",
    "venue_fixed_timings_start_time",
    "venue_fixed_timings_end_time",
    "venue_mixed_timings_monday_start_time",
    "venue_mixed_timings_monday_end_time",
    "venue_mixed_timings_tuesday_start_time",
    "venue_mixed_timings_tuesday_end_time",
    "venue_mixed_timings_wednesday_start_time",
    "venue_mixed_timings_wednesday_end_time",
    "venue_mixed_timings_thursday_start_time",
    "venue_mixed_timings_thursday_end_time",
    "venue_mixed_timings_friday_start_time",
    "venue_mixed_timings_friday_end_time",
    "venue_mixed_timings_saturday_start_time",
    "venue_mixed_timings_saturday_end_time",
    "venue_mixed_timings_sunday_start_time",
    "venue_mixed_timings_sunday_end_time",
    "venue_entry_cost",
    "ticketing_requirement",
    "venue_booking_type",
    "ticketing_variants",
    "ticket_variant_definition_baby",
    "ticket_variant_baby_price",
    "ticket_variant_definition__fixed_child",
    "ticket_variant_fixed_child_price",
    "ticket_variant_definition_young_child",
    "ticket_variant_young_child_price",
    "ticket_variant_definition_older_child",
    "ticket_variant_older_child_price",
    "ticket_variant_definition_adult",
    "ticket_variant_adult_price",
    "ticket_variant_definition_concession",
    "ticket_variant_concession_price",
    "ticket_variant_definition_group",
    "ticket_variant_group_price",
    "venue_general_facilities",
    "venue_child_facilities",
    "venue_adult_facilities",
    "venue_dog_facilities",
    "venue_parking_provision",
    "venue_age_suitability_under_1_s",
    "venue_age_suitability_1_to_2_years",
    "venue_age_suitability_3_to_4_years",
    "venue_age_suitability_5_to_7_years",
    "venue_age_suitability_8_to_12_years",
    "venue_age_suitability_over_13_years",
    "venue_age_suitability_adults",
    "venue_physical_setting",
    "venue_detailed_weather_suitability",
    "venue_estimated_duration",
    "venue_interest_tags",
    "venue_seasonal_tag",
    "venue_seasonal_highlights",
    "venue_attractions",
    "venue_extra_kit",
    "image",
    "createdAt",
    "updatedAt"
)
SELECT
    "id",
    "opportunity_type",
    "venue_opportunity_theme_id",
    "venue_opportunity_theme_variant_id",
    "venue_name",
    "venue_activity_group",
    "venue_description",
    "venue_address_line_1",
    "venue_address_line_2",
    "venue_city",
    "venue_region",
    "venue_postcode",
    "latitude",
    "longitude",
    "venue_country",
    "venue_schedule_pattern",
    "venue_fixed_daily_timings",
    "venue_fixed_timings_start_time",
    "venue_fixed_timings_end_time",
    "venue_mixed_timings_monday_start_time",
    "venue_mixed_timings_monday_end_time",
    "venue_mixed_timings_tuesday_start_time",
    "venue_mixed_timings_tuesday_end_time",
    "venue_mixed_timings_wednesday_start_time",
    "venue_mixed_timings_wednesday_end_time",
    "venue_mixed_timings_thursday_start_time",
    "venue_mixed_timings_thursday_end_time",
    "venue_mixed_timings_friday_start_time",
    "venue_mixed_timings_friday_end_time",
    "venue_mixed_timings_saturday_start_time",
    "venue_mixed_timings_saturday_end_time",
    "venue_mixed_timings_sunday_start_time",
    "venue_mixed_timings_sunday_end_time",
    "venue_entry_cost",
    "ticketing_requirement",
    "venue_booking_type",
    "ticketing_variants",
    "ticket_variant_definition_baby",
    "ticket_variant_baby_price",
    "ticket_variant_definition__fixed_child",
    "ticket_variant_fixed_child_price",
    "ticket_variant_definition_young_child",
    "ticket_variant_young_child_price",
    "ticket_variant_definition_older_child",
    "ticket_variant_older_child_price",
    "ticket_variant_definition_adult",
    "ticket_variant_adult_price",
    "ticket_variant_definition_concession",
    "ticket_variant_concession_price",
    "ticket_variant_definition_group",
    "ticket_variant_group_price",
    "venue_general_facilities",
    "venue_child_facilities",
    "venue_adult_facilities",
    "venue_dog_facilities",
    "venue_parking_provision",
    "venue_age_suitability_under_1_s",
    "venue_age_suitability_1_to_2_years",
    "venue_age_suitability_3_to_4_years",
    "venue_age_suitability_5_to_7_years",
    "venue_age_suitability_8_to_12_years",
    "venue_age_suitability_over_13_years",
    "venue_age_suitability_adults",
    "venue_physical_setting",
    "venue_detailed_weather_suitability",
    "venue_estimated_duration",
    "venue_interest_tags",
    "venue_seasonal_tag",
    "venue_seasonal_highlights",
    "venue_attractions",
    "venue_extra_kit",
    "image",
    "createdAt",
    "updatedAt"
FROM "opportunity_venue_v2_old";

DROP TABLE "opportunity_venue_v2_old";

CREATE INDEX "opportunity_venue_v2_venue_opportunity_theme_id_idx" ON "opportunity_venue_v2"("venue_opportunity_theme_id");

CREATE INDEX "opportunity_venue_v2_venue_opportunity_theme_variant_id_idx" ON "opportunity_venue_v2"("venue_opportunity_theme_variant_id");

ALTER TABLE "opportunity_venue_v2" ADD CONSTRAINT "opportunity_venue_v2_venue_opportunity_theme_id_fkey" FOREIGN KEY ("venue_opportunity_theme_id") REFERENCES "opportunity_theme"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "opportunity_venue_v2" ADD CONSTRAINT "opportunity_venue_v2_venue_opportunity_theme_variant_id_fkey" FOREIGN KEY ("venue_opportunity_theme_variant_id") REFERENCES "opportunity_theme_variant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
