import type { OpportunityClubV2Response } from "./types.js";

const s = (v: unknown): string | null => (typeof v === "string" && v !== "" ? v : null);
const b = (v: unknown): boolean | null => (typeof v === "boolean" ? v : null);
const n = (v: unknown): number | null => (typeof v === "number" ? v : null);
const d = (v: unknown): Date | null => (v != null ? new Date(v as string) : null);

export function enrichOpportunityClubV2Response(
  item: Record<string, unknown>,
): OpportunityClubV2Response {
  const themeSlug = (item.themeSlug as string) ?? "";
  const themeVariantSlug = (item.themeVariantSlug as string) ?? "";
  const oppType = (item.opportunityType as string) ?? "club";

  return {
    id: item.id as string,
    opportunityType: oppType,
    theme: {
      id: themeSlug,
      slug: themeSlug,
      name: themeSlug,
      recordType: oppType,
    },
    themeVariant: {
      id: themeVariantSlug,
      slug: themeVariantSlug,
      name: themeVariantSlug,
    },
    clubName: (item.clubName as string) ?? "",
    clubDescription: s(item.clubDescription),
    clubFormat: s(item.clubFormat),
    clubCommittment: s(item.clubCommittment),
    clubFrequency: s(item.clubFrequency),
    clubAddressLine1: s(item.clubAddressLine1),
    clubAddressLine2: s(item.clubAddressLine2),
    clubCityTown: s(item.clubCityTown),
    clubStateRegionProvince: s(item.clubStateRegionProvince),
    clubPostcode: s(item.clubPostcode),
    clubCountry: s(item.clubCountry),
    latitude: s(item.latitude),
    longitude: s(item.longitude),
    clubStartDate: d(item.clubStartDate),
    clubEndDate: d(item.clubEndDate),
    clubRepeatSession: b(item.clubRepeatSession),
    clubDailyFixedSessionTotal: n(item.clubDailyFixedSessionTotal),
    clubDailyFixedSessionSchedule: s(item.clubDailyFixedSessionSchedule),
    clubDailySchedule: s(item.clubDailySchedule),
    clubFixedDailyTimings: b(item.clubFixedDailyTimings),
    clubDailyStartTime: s(item.clubDailyStartTime),
    clubDailyEndTime: s(item.clubDailyEndTime),
    clubMixedTimingsMondayStartTime: s(item.clubMixedTimingsMondayStartTime),
    clubMixedTimingsMondayEndTime: s(item.clubMixedTimingsMondayEndTime),
    clubMixedTimingsTuesdayStartTime: s(item.clubMixedTimingsTuesdayStartTime),
    clubMixedTimingsTuesdayEndTime: s(item.clubMixedTimingsTuesdayEndTime),
    clubMixedTimingsWednesdayStartTime: s(item.clubMixedTimingsWednesdayStartTime),
    clubMixedTimingsWednesdayEndTime: s(item.clubMixedTimingsWednesdayEndTime),
    clubMixedTimingsThursdayStartTime: s(item.clubMixedTimingsThursdayStartTime),
    clubMixedTimingsThursdayEndTime: s(item.clubMixedTimingsThursdayEndTime),
    clubMixedTimingsFridayStartTime: s(item.clubMixedTimingsFridayStartTime),
    clubMixedTimingsFridayEndTime: s(item.clubMixedTimingsFridayEndTime),
    clubMixedTimingsSaturdayStartTime: s(item.clubMixedTimingsSaturdayStartTime),
    clubMixedTimingsSaturdayEndTime: s(item.clubMixedTimingsSaturdayEndTime),
    clubMixedTimingsSundayStartTime: s(item.clubMixedTimingsSundayStartTime),
    clubMixedTimingsSundayEndTime: s(item.clubMixedTimingsSundayEndTime),
    clubMultiSessionMondaySessionTotal: n(item.clubMultiSessionMondaySessionTotal),
    clubMultiSessionMondaySchedule: s(item.clubMultiSessionMondaySchedule),
    clubMultiSessionTuesdaySessionTotal: n(item.clubMultiSessionTuesdaySessionTotal),
    clubMultiSessionTuesdaySchedule: s(item.clubMultiSessionTuesdaySchedule),
    clubMultiSessionWednesdaySessionTotal: n(item.clubMultiSessionWednesdaySessionTotal),
    clubMultiSessionWednesdaySchedule: s(item.clubMultiSessionWednesdaySchedule),
    clubMultiSessionThursdaySessionTotal: n(item.clubMultiSessionThursdaySessionTotal),
    clubMultiSessionThursdaySchedule: s(item.clubMultiSessionThursdaySchedule),
    clubMultiSessionFridaySessionTotal: n(item.clubMultiSessionFridaySessionTotal),
    clubMultiSessionFridaySchedule: s(item.clubMultiSessionFridaySchedule),
    clubMultiSessionSaturdaySessionTotal: n(item.clubMultiSessionSaturdaySessionTotal),
    clubMultiSessionSaturdaySchedule: s(item.clubMultiSessionSaturdaySchedule),
    clubMultiSessionSundaySessionTotal: n(item.clubMultiSessionSundaySessionTotal),
    clubMultiSessionSundaySchedule: s(item.clubMultiSessionSundaySchedule),
    clubMonthlySchedule: s(item.clubMonthlySchedule),
    clubFixedMonthOccurance: s(item.clubFixedMonthOccurance),
    clubMonthlyOccurance: s(item.clubMonthlyOccurance),
    clubMonthlyFixedDates: s(item.clubMonthlyFixedDates),
    ticketingRequirement: b(item.ticketingRequirement),
    clubBookingProvision: s(item.clubBookingProvision),
    ticketingVariants: s(item.ticketingVariants),
    ticketVariantDefinitionBaby: s(item.ticketVariantDefinitionBaby),
    ticketVariantBabyPrice: s(item.ticketVariantBabyPrice),
    ticketVariantDefinitionFixedChild: s(item.ticketVariantDefinitionFixedChild),
    ticketVariantFixedChildPrice: s(item.ticketVariantFixedChildPrice),
    ticketVariantDefinitionYoungChild: s(item.ticketVariantDefinitionYoungChild),
    ticketVariantYoungChildPrice: s(item.ticketVariantYoungChildPrice),
    ticketVariantDefinitionOlderChild: s(item.ticketVariantDefinitionOlderChild),
    ticketVariantOlderChildPrice: s(item.ticketVariantOlderChildPrice),
    ticketVariantDefinitionAdult: s(item.ticketVariantDefinitionAdult),
    ticketVariantAdultPrice: s(item.ticketVariantAdultPrice),
    ticketVariantDefinitionConcession: s(item.ticketVariantDefinitionConcession),
    ticketVariantConcessionPrice: s(item.ticketVariantConcessionPrice),
    ticketVariantDefinitionGroup: s(item.ticketVariantDefinitionGroup),
    ticketVariantGroupPrice: s(item.ticketVariantGroupPrice),
    clubParkingProvision: s(item.clubParkingProvision),
    clubGeneralFacilities: s(item.clubGeneralFacilities),
    clubChildFacilities: s(item.clubChildFacilities),
    clubAdultFacilities: s(item.clubAdultFacilities),
    clubAgeSuitabilityUnder1S: b(item.clubAgeSuitabilityUnder1S),
    clubAgeSuitability1To2Years: b(item.clubAgeSuitability1To2Years),
    clubAgeSuitability3To4Years: b(item.clubAgeSuitability3To4Years),
    clubAgeSuitability5To7Years: b(item.clubAgeSuitability5To7Years),
    clubAgeSuitability8To12Years: b(item.clubAgeSuitability8To12Years),
    clubAgeSuitabilityOver13Years: b(item.clubAgeSuitabilityOver13Years),
    clubAgeSuitabilityAdults: b(item.clubAgeSuitabilityAdults),
    clubActivityGroup: s(item.clubActivityGroup),
    clubPhysicalSetting: s(item.clubPhysicalSetting),
    clubSkillArea: s(item.clubSkillArea),
    clubSkillAreaVariant: s(item.clubSkillAreaVariant),
    clubAbilityLevel: s(item.clubAbilityLevel),
    clubInterestTags: s(item.clubInterestTags),
    clubSeasonalTag: s(item.clubSeasonalTag),
    clubSeasonalHighlights: s(item.clubSeasonalHighlights),
    clubAttractions: s(item.clubAttractions),
    clubExtraKit: s(item.clubExtraKit),
    image: s(item.image),
    createdAt: new Date(item.createdAt as string),
    updatedAt: new Date(item.updatedAt as string),
  };
}
