-- Dedicated `opportunity_events_v2` table; `opportunity_venues_v2` is venue-only again.
-- Migrates rows where `opportunity_type = 'event'`, then drops merged event columns from venues.

DROP VIEW IF EXISTS "events_v2";

CREATE TABLE "opportunity_events_v2" (
    "id" TEXT NOT NULL,
    "opportunity_type" "OpportunityRecordType" NOT NULL DEFAULT 'event',
    "event_opportunity_theme_id" TEXT NOT NULL,
    "event_opportunity_theme_variant_id" TEXT NOT NULL,
    "event_name" TEXT NOT NULL,
    "event_activity_group" TEXT,
    "event_type" TEXT,
    "event_description" TEXT,
    "event_address_line_1" TEXT,
    "event_address_line_2" TEXT,
    "event_city" TEXT,
    "event_region" TEXT,
    "event_postcode" VARCHAR(20),
    "latitude" TEXT,
    "longitude" TEXT,
    "event_country" TEXT,
    "event_physical_setting" TEXT,
    "event_detailed_weather_suitability" TEXT,
    "event_start_date" TIMESTAMP(3),
    "event_end_date" TIMESTAMP(3),
    "event_days_total" INTEGER,
    "event_daily_multi_session" BOOLEAN,
    "event_timetable_weekly" TEXT,
    "event_daily_fixed_timings" BOOLEAN,
    "event_daily_fixed_start_time" VARCHAR(5),
    "event_daily_fixed_end_time" VARCHAR(5),
    "event_daily_multi_session_total" INTEGER,
    "event_daily_multi_session_timings" TEXT,
    "event_weekly_fixed_start_time" VARCHAR(5),
    "event_weekly_fixed_end_time" VARCHAR(5),
    "event_mixed_timings_monday_start_time" VARCHAR(5),
    "event_mixed_timings_monday_end_time" VARCHAR(5),
    "event_mixed_timings_tuesday_start_time" VARCHAR(5),
    "event_mixed_timings_tuesday_end_time" VARCHAR(5),
    "event_mixed_timings_wednesday_start_time" VARCHAR(5),
    "event_mixed_timings_wednesday_end_time" VARCHAR(5),
    "event_mixed_timings_thursday_start_time" VARCHAR(5),
    "event_mixed_timings_thursday_end_time" VARCHAR(5),
    "event_mixed_timings_friday_start_time" VARCHAR(5),
    "event_mixed_timings_friday_end_time" VARCHAR(5),
    "event_mixed_timings_saturday_start_time" VARCHAR(5),
    "event_mixed_timings_saturday_end_time" VARCHAR(5),
    "event_mixed_timings_sunday_start_time" VARCHAR(5),
    "event_mixed_timings_sunday_end_time" VARCHAR(5),
    "event_entry_cost" BOOLEAN,
    "ticketing_requirement" BOOLEAN,
    "event_booking_type" TEXT,
    "ticketing_variants" TEXT,
    "ticket_variant_definition_baby" TEXT,
    "ticket_variant_baby_price" TEXT,
    "ticket_variant_definition__fixed_child" TEXT,
    "ticket_variant_fixed_child_price" TEXT,
    "ticket_variant_definition_young_child" TEXT,
    "ticket_variant_young_child_price" TEXT,
    "ticket_variant_definition_older_child" TEXT,
    "ticket_variant_older_child_price" TEXT,
    "ticket_variant_definition_adult" TEXT,
    "ticket_variant_adult_price" TEXT,
    "ticket_variant_definition_concession" TEXT,
    "ticket_variant_concession_price" TEXT,
    "ticket_variant_definition_group" TEXT,
    "ticket_variant_group_price" TEXT,
    "ticket_sales_start_date" TIMESTAMP(3),
    "event_parking_provision" TEXT,
    "event_general_facilities" TEXT,
    "event_child_facilities" TEXT,
    "event_adult_facilities" TEXT,
    "event_age_suitability_under_1_s" BOOLEAN,
    "event_age_suitability_1_to_2_years" BOOLEAN,
    "event_age_suitability_3_to_4_years" BOOLEAN,
    "event_age_suitability_5_to_7_years" BOOLEAN,
    "event_age_suitability_8_to_12_years" BOOLEAN,
    "event_age_suitability_over_13_years" BOOLEAN,
    "event_age_suitability_adults" BOOLEAN,
    "event_interest_tags" TEXT,
    "event_seasonal_tags" TEXT,
    "event_seasonal_highlights" TEXT,
    "event_highlights" TEXT,
    "event_extra_kit" TEXT,
    "event_skill_area" TEXT,
    "event_skill_area_variant" TEXT,
    "event_ability_level" TEXT,
    "image" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "opportunity_events_v2_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "opportunity_events_v2_event_opportunity_theme_id_idx" ON "opportunity_events_v2"("event_opportunity_theme_id");

CREATE INDEX "opportunity_events_v2_event_opportunity_theme_variant_id_idx" ON "opportunity_events_v2"("event_opportunity_theme_variant_id");

CREATE INDEX "opportunity_events_v2_opportunity_type_idx" ON "opportunity_events_v2"("opportunity_type");

ALTER TABLE "opportunity_events_v2" ADD CONSTRAINT "opportunity_events_v2_event_opportunity_theme_id_fkey" FOREIGN KEY ("event_opportunity_theme_id") REFERENCES "opportunity_theme"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "opportunity_events_v2" ADD CONSTRAINT "opportunity_events_v2_event_opportunity_theme_variant_id_fkey" FOREIGN KEY ("event_opportunity_theme_variant_id") REFERENCES "opportunity_theme_variant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

INSERT INTO "opportunity_events_v2" (
    "id",
    "opportunity_type",
    "event_opportunity_theme_id",
    "event_opportunity_theme_variant_id",
    "event_name",
    "event_activity_group",
    "event_type",
    "event_description",
    "event_address_line_1",
    "event_address_line_2",
    "event_city",
    "event_region",
    "event_postcode",
    "latitude",
    "longitude",
    "event_country",
    "event_physical_setting",
    "event_detailed_weather_suitability",
    "event_start_date",
    "event_end_date",
    "event_days_total",
    "event_daily_multi_session",
    "event_timetable_weekly",
    "event_daily_fixed_timings",
    "event_daily_fixed_start_time",
    "event_daily_fixed_end_time",
    "event_daily_multi_session_total",
    "event_daily_multi_session_timings",
    "event_weekly_fixed_start_time",
    "event_weekly_fixed_end_time",
    "event_mixed_timings_monday_start_time",
    "event_mixed_timings_monday_end_time",
    "event_mixed_timings_tuesday_start_time",
    "event_mixed_timings_tuesday_end_time",
    "event_mixed_timings_wednesday_start_time",
    "event_mixed_timings_wednesday_end_time",
    "event_mixed_timings_thursday_start_time",
    "event_mixed_timings_thursday_end_time",
    "event_mixed_timings_friday_start_time",
    "event_mixed_timings_friday_end_time",
    "event_mixed_timings_saturday_start_time",
    "event_mixed_timings_saturday_end_time",
    "event_mixed_timings_sunday_start_time",
    "event_mixed_timings_sunday_end_time",
    "event_entry_cost",
    "ticketing_requirement",
    "event_booking_type",
    "ticketing_variants",
    "ticket_variant_definition_baby",
    "ticket_variant_baby_price",
    "ticket_variant_definition__fixed_child",
    "ticket_variant_fixed_child_price",
    "ticket_variant_definition_young_child",
    "ticket_variant_young_child_price",
    "ticket_variant_definition_older_child",
    "ticket_variant_older_child_price",
    "ticket_variant_definition_adult",
    "ticket_variant_adult_price",
    "ticket_variant_definition_concession",
    "ticket_variant_concession_price",
    "ticket_variant_definition_group",
    "ticket_variant_group_price",
    "ticket_sales_start_date",
    "event_parking_provision",
    "event_general_facilities",
    "event_child_facilities",
    "event_adult_facilities",
    "event_age_suitability_under_1_s",
    "event_age_suitability_1_to_2_years",
    "event_age_suitability_3_to_4_years",
    "event_age_suitability_5_to_7_years",
    "event_age_suitability_8_to_12_years",
    "event_age_suitability_over_13_years",
    "event_age_suitability_adults",
    "event_interest_tags",
    "event_seasonal_tags",
    "event_seasonal_highlights",
    "event_highlights",
    "event_extra_kit",
    "event_skill_area",
    "event_skill_area_variant",
    "event_ability_level",
    "image",
    "createdAt",
    "updatedAt"
)
SELECT
    v."id",
    'event'::"OpportunityRecordType",
    v."venue_opportunity_theme_id",
    v."venue_opportunity_theme_variant_id",
    COALESCE(v."event_name", ''),
    v."event_activity_group",
    v."event_type",
    v."event_description",
    v."event_address_line_1",
    v."event_address_line_2",
    v."event_city",
    v."event_region",
    v."event_postcode",
    v."latitude",
    v."longitude",
    v."event_country",
    v."event_physical_setting",
    v."event_detailed_weather_suitability",
    v."event_start_date",
    v."event_end_date",
    v."event_days_total",
    v."event_daily_multi_session",
    v."event_timetable_weekly",
    v."event_daily_fixed_timings",
    v."event_daily_fixed_start_time",
    v."event_daily_fixed_end_time",
    v."event_daily_multi_session_total",
    v."event_daily_multi_session_timings",
    v."event_weekly_fixed_start_time",
    v."event_weekly_fixed_end_time",
    v."event_mixed_timings_monday_start_time",
    v."event_mixed_timings_monday_end_time",
    v."event_mixed_timings_tuesday_start_time",
    v."event_mixed_timings_tuesday_end_time",
    v."event_mixed_timings_wednesday_start_time",
    v."event_mixed_timings_wednesday_end_time",
    v."event_mixed_timings_thursday_start_time",
    v."event_mixed_timings_thursday_end_time",
    v."event_mixed_timings_friday_start_time",
    v."event_mixed_timings_friday_end_time",
    v."event_mixed_timings_saturday_start_time",
    v."event_mixed_timings_saturday_end_time",
    v."event_mixed_timings_sunday_start_time",
    v."event_mixed_timings_sunday_end_time",
    v."event_entry_cost",
    v."ticketing_requirement",
    v."event_booking_type",
    v."ticketing_variants",
    v."ticket_variant_definition_baby",
    v."ticket_variant_baby_price",
    v."ticket_variant_definition__fixed_child",
    v."ticket_variant_fixed_child_price",
    v."ticket_variant_definition_young_child",
    v."ticket_variant_young_child_price",
    v."ticket_variant_definition_older_child",
    v."ticket_variant_older_child_price",
    v."ticket_variant_definition_adult",
    v."ticket_variant_adult_price",
    v."ticket_variant_definition_concession",
    v."ticket_variant_concession_price",
    v."ticket_variant_definition_group",
    v."ticket_variant_group_price",
    v."ticket_sales_start_date",
    v."event_parking_provision",
    v."event_general_facilities",
    v."event_child_facilities",
    v."event_adult_facilities",
    v."event_age_suitability_under_1_s",
    v."event_age_suitability_1_to_2_years",
    v."event_age_suitability_3_to_4_years",
    v."event_age_suitability_5_to_7_years",
    v."event_age_suitability_8_to_12_years",
    v."event_age_suitability_over_13_years",
    v."event_age_suitability_adults",
    v."event_interest_tags",
    v."event_seasonal_tags",
    v."event_seasonal_highlights",
    v."event_highlights",
    v."event_extra_kit",
    v."event_skill_area",
    v."event_skill_area_variant",
    v."event_ability_level",
    v."image",
    v."createdAt",
    v."updatedAt"
FROM "opportunity_venues_v2" v
WHERE v."opportunity_type" = 'event';

DELETE FROM "opportunity_venues_v2" WHERE "opportunity_type" = 'event';

DROP INDEX IF EXISTS "opportunity_venues_v2_opportunity_type_idx";

ALTER TABLE "opportunity_venues_v2"
    DROP COLUMN IF EXISTS "opportunity_type",
    DROP COLUMN IF EXISTS "event_name",
    DROP COLUMN IF EXISTS "event_activity_group",
    DROP COLUMN IF EXISTS "event_type",
    DROP COLUMN IF EXISTS "event_description",
    DROP COLUMN IF EXISTS "event_address_line_1",
    DROP COLUMN IF EXISTS "event_address_line_2",
    DROP COLUMN IF EXISTS "event_city",
    DROP COLUMN IF EXISTS "event_region",
    DROP COLUMN IF EXISTS "event_postcode",
    DROP COLUMN IF EXISTS "event_country",
    DROP COLUMN IF EXISTS "event_physical_setting",
    DROP COLUMN IF EXISTS "event_detailed_weather_suitability",
    DROP COLUMN IF EXISTS "event_start_date",
    DROP COLUMN IF EXISTS "event_end_date",
    DROP COLUMN IF EXISTS "event_days_total",
    DROP COLUMN IF EXISTS "event_daily_multi_session",
    DROP COLUMN IF EXISTS "event_timetable_weekly",
    DROP COLUMN IF EXISTS "event_daily_fixed_timings",
    DROP COLUMN IF EXISTS "event_daily_fixed_start_time",
    DROP COLUMN IF EXISTS "event_daily_fixed_end_time",
    DROP COLUMN IF EXISTS "event_daily_multi_session_total",
    DROP COLUMN IF EXISTS "event_daily_multi_session_timings",
    DROP COLUMN IF EXISTS "event_weekly_fixed_start_time",
    DROP COLUMN IF EXISTS "event_weekly_fixed_end_time",
    DROP COLUMN IF EXISTS "event_mixed_timings_monday_start_time",
    DROP COLUMN IF EXISTS "event_mixed_timings_monday_end_time",
    DROP COLUMN IF EXISTS "event_mixed_timings_tuesday_start_time",
    DROP COLUMN IF EXISTS "event_mixed_timings_tuesday_end_time",
    DROP COLUMN IF EXISTS "event_mixed_timings_wednesday_start_time",
    DROP COLUMN IF EXISTS "event_mixed_timings_wednesday_end_time",
    DROP COLUMN IF EXISTS "event_mixed_timings_thursday_start_time",
    DROP COLUMN IF EXISTS "event_mixed_timings_thursday_end_time",
    DROP COLUMN IF EXISTS "event_mixed_timings_friday_start_time",
    DROP COLUMN IF EXISTS "event_mixed_timings_friday_end_time",
    DROP COLUMN IF EXISTS "event_mixed_timings_saturday_start_time",
    DROP COLUMN IF EXISTS "event_mixed_timings_saturday_end_time",
    DROP COLUMN IF EXISTS "event_mixed_timings_sunday_start_time",
    DROP COLUMN IF EXISTS "event_mixed_timings_sunday_end_time",
    DROP COLUMN IF EXISTS "event_entry_cost",
    DROP COLUMN IF EXISTS "event_booking_type",
    DROP COLUMN IF EXISTS "event_parking_provision",
    DROP COLUMN IF EXISTS "event_general_facilities",
    DROP COLUMN IF EXISTS "event_child_facilities",
    DROP COLUMN IF EXISTS "event_adult_facilities",
    DROP COLUMN IF EXISTS "event_age_suitability_under_1_s",
    DROP COLUMN IF EXISTS "event_age_suitability_1_to_2_years",
    DROP COLUMN IF EXISTS "event_age_suitability_3_to_4_years",
    DROP COLUMN IF EXISTS "event_age_suitability_5_to_7_years",
    DROP COLUMN IF EXISTS "event_age_suitability_8_to_12_years",
    DROP COLUMN IF EXISTS "event_age_suitability_over_13_years",
    DROP COLUMN IF EXISTS "event_age_suitability_adults",
    DROP COLUMN IF EXISTS "event_interest_tags",
    DROP COLUMN IF EXISTS "event_seasonal_tags",
    DROP COLUMN IF EXISTS "event_seasonal_highlights",
    DROP COLUMN IF EXISTS "event_highlights",
    DROP COLUMN IF EXISTS "event_extra_kit",
    DROP COLUMN IF EXISTS "event_skill_area",
    DROP COLUMN IF EXISTS "event_skill_area_variant",
    DROP COLUMN IF EXISTS "event_ability_level";

ALTER TABLE "opportunity_venues_v2" ALTER COLUMN "venue_name" SET NOT NULL;
